### ISSUE TITLE
Error: No data available for version undefined

### ISSUE THREAD

**Issue by mirkokral** [PrismarineJS/node-minecraft-protocol#1032]
[X] The [FAQ](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - minecraft-protocol: Latest (as of this post)
 - server: paper - scissors 
 - node: v18.7.0

## Detailed description of a problem
A clear and concise description of what the problem is.

## Current code
```ts
import path = require("path");

const EventEmmiter = require("events");
export class MinecraftLogoutError extends Error {
  constructor(message) {
    super(message); // (1)
    this.name = "MinecraftLogoutError"; // (2)
  }
}
export class Bot extends EventEmmiter {
  _client: any = null;
  host: string = null;
  port: number = null;
  loginInterval: number = null;
  _queue: Array<string> = [];
  serverName: string = null;
  plugins: Array<any> = [];
  minecraftPluginHandler: Object = {};
  constructor(
    host: string,
    port: number,
    loginInterval?: number,
    serverName?: string
  ) {
    super();
    this.host = host;
    this.port = port;
    this.serverName = serverName ?? "Unnamed server";
    this.loginInterval = loginInterval ?? 5000;
    const mcp = require("minecraft-protocol");
    const rs = require("randomstring");
    const Logger = require("./logger");
    const fs = require("fs");
    const logger = new Logger.Logger({});
    const random = require("./random");
    const prismarinechat = require("prismarine-chat");
    fs.readdirSync(path.join(__dirname, "../plugins")).forEach((file) => {
      if (file.endsWith(".js")) {
        const plugin = require(path.join(__dirname, "../plugins", file));
        this.plugins.push(plugin);
      }
    });
    this._client = new mcp.Client({
      host: host,
      port: port,
      username: rs.generate(random.RandomInt(3, 16)),
      version: '1.18.2'
    });
    this._client.on("error", (err) => {
      logger.error(err);
    });
    this._client.on("chat", (message) => {
      try {
        this.emit("chat", new prismarinechat(message));
      } catch (e) {
        this.emit("error", e);
      }
    });
    this._client.on("login", (data) => {
      this.minecraftPluginHandler = {process, bot: this};
      logger.log(`Logged in as ${data.username}`);
      this.emit("login", data);
      setInterval(() => {
        this._client.write("chat", {
          message: this._queue.shift(),
        });
      }, 200);
      this.plugins.forEach((e) => {
        new e().onLogin(this.minecraftPluginHandler);
      });
    });
    this.on('chat', (message) => {
      this.plugins.forEach((e) => {
        new e().onChat(this.minecraftPluginHandler, message);
      }
    );
    })
    this._client.on("end", (e) => {
      logger.warn(
        `Bot at ${
          this.host
        } disconnected unexpectedly, the server provided a reason: ${require("util").inspect(
          e
        )} and the bot will reconnect in a bit.`
      );
      setTimeout(() => {
        var newBot = new Bot(this.host, this.port);
        this.emit("newbot", newBot);
      }, this.loginInterval);
    });
  }
  async chat(message) {
    this._queue.push(message);
  }
}
```

## Expected behavior
The bot will log in and start logging the chat.

## Additional context
Here is the error:
```
/mnt/c/Users/mirko/Documents/Projects/MBot/node_modules/minecraft-protocol/src/transforms/serializer.js:21
    throw new Error(`No data available for version ${version}`)
          ^

Error: No data available for version undefined
    at createProtocol (/mnt/c/Users/mirko/Documents/Projects/MBot/node_modules/minecraft-protocol/src/transforms/serializer.js:21:11)
    at createSerializer (/mnt/c/Users/mirko/Documents/Projects/MBot/node_modules/minecraft-protocol/src/transforms/serializer.js:41:25)
    at Client.setSerializer (/mnt/c/Users/mirko/Documents/Projects/MBot/node_modules/minecraft-protocol/src/client.js:42:23)
    at set state [as state] (/mnt/c/Users/mirko/Documents/Projects/MBot/node_modules/minecraft-protocol/src/client.js:113:10)
    at new Client (/mnt/c/Users/mirko/Documents/Projects/MBot/node_modules/minecraft-protocol/src/client.js:34:16)
    at new Bot (/mnt/c/Users/mirko/Documents/Projects/MBot/build/lib/bot.js:96:25)
    at BotCreator.<anonymous> (/mnt/c/Users/mirko/Documents/Projects/MBot/build/lib/BotCreator.js:53:31)
    at step (/mnt/c/Users/mirko/Documents/Projects/MBot/build/lib/BotCreator.js:32:23)
    at Object.next (/mnt/c/Users/mirko/Documents/Projects/MBot/build/lib/BotCreator.js:13:53)
    at fulfilled (/mnt/c/Users/mirko/Documents/Projects/MBot/build/lib/BotCreator.js:4:58)

Node.js v18.7.0
```

**Comment by mirkokral** [comment]
ok i fixed via tracking down error using vscode debugger and adding ` ?? '1.18.2'` at the end of "version"

**Comment by mirkokral** [comment]
oh ik i did new Client but u do mc.createClient
