### ISSUE TITLE
Custom channel registration fails

### ISSUE THREAD

**Issue by turikhay** [PrismarineJS/node-minecraft-protocol#1095]
- [x] The [FAQ](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - minecraft-protocol: 1.41.2
 - server: vanilla/spigot/paper 1.13+
 - node: 18.15.0

## Detailed description of a problem
I'm currently working on a bot that automatically tests whether the server sends correct response using a plugin channel (see [here](https://github.com/turikhay/MapModCompanion/blob/main/tests_e2e/bot/tests/xaero/common.mjs)). If I understand correctly, the proper way to register a custom channel is:
```js
client.on("login", () => {
    client.registerChannel(channel, typeDef, /* custom? */ true)
})
```

However, whenever I do this, I get the following error:
```
/usr/src/app/node_modules/.pnpm/protodef@1.15.0/node_modules/protodef/src/protodef.js:141
        throw e
        ^

Error: SizeOf error for undefined : missing data type: minecraft:register
    at ProtoDef.sizeOf (/usr/src/app/node_modules/.pnpm/protodef@1.15.0/node_modules/protodef/src/protodef.js:128:13)
    at e.message (/usr/src/app/node_modules/.pnpm/protodef@1.15.0/node_modules/protodef/src/protodef.js:138:40)
    at tryCatch (/usr/src/app/node_modules/.pnpm/protodef@1.15.0/node_modules/protodef/src/utils.js:50:16)
    at ProtoDef.createPacketBuffer (/usr/src/app/node_modules/.pnpm/protodef@1.15.0/node_modules/protodef/src/protodef.js:138:20)
    at Client.writeChannel (/usr/src/app/node_modules/.pnpm/minecraft-protocol@1.41.1/node_modules/minecraft-protocol/src/client/pluginChannels.js:77:19)
    at Client.registerChannel (/usr/src/app/node_modules/.pnpm/minecraft-protocol@1.41.1/node_modules/minecraft-protocol/src/client/pluginChannels.js:28:14)
    at Client.<anonymous> (file:///usr/src/app/tests/xaero/common.mjs:9:12)
    at Object.onceWrapper (node:events:628:26)
    at Client.emit (node:events:525:35)
    at FullPacketParser.<anonymous> (/usr/src/app/node_modules/.pnpm/minecraft-protocol@1.41.1/node_modules/minecraft-protocol/src/client.js:91:12)

Node.js v18.15.0
```

**Comment by turikhay** [comment]
Currently proposed workaround:

https://github.com/turikhay/MapModCompanion/blob/e007bbf5118b4c43267234465c81684d5a9522eb/tests_e2e/bot/testClient.mjs#L47-L50
