### ISSUE TITLE
Error connect to server.

### ISSUE THREAD

**Issue by AssainOfTheMist** [PrismarineJS/node-minecraft-protocol#1100]
## Versions
 - minecraft-protocol: 1.14.2
 - server: vanilla
 - node: 16.14.0
 - version minecraft: 1.19

## Detailed description of a problem
Error connect the client.
```
Disconnecting client because error TypeError [ERR_INVALID_ARG_TYPE]: Serialization error for play.toClient : SizeOf error for undefined : The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received undefined
	at new NodeError(node:internal/errors:371:5)
	at Function.byteLength (node:buffer:734:11)
	at Object.string (eval at compile (C:\Users\user\node_modules\protodef\src\compiler.js:258:12), <anonymous>:45:25)
	at Object.packet_login (eval at compile (C:\Users\user\node_modules\protodef\src\compiler.js:258:12), <anonymous>:1302:27)
	at eval (eval at compile (C:\Users\user\node_modules\protodef\src\compiler.js:258:12), <anonymous>:2598:50)
	at packet (eval at compile (C:\Users\user\node_modules\protodef\src\compiler.js:258:12), <anonymous>:2670:9)
	at CompiledProtodef.sizeOf (C:\Users\user\node_modules\protodef\src\compiler.js:89:14)
	at e.message (C:\Users\user\node_modules\protodef\src\compiler.js:96:40)
	at tryCatch (C:\Users\user\node_modules\protodef\src\utils.js:50:16)
	at CompiledProtodef.createPacketBuffer (C:\Users\user\node_modules\protodef\src\compiler.js:96:20) {
	code 'ERR_INVALID_ARG_TYPE',
	field: 'play.toClient'
}
```

## Current code
```js
const mc = require('minecraft-protocol');
const server = mc.createServer({
  'online-mode': false,   // optional
  encryption: true,      // optional
  host: 'localhost',       // optional
  port: 25565,           // optional
  version: '1.19'
});
const mcData = require('minecraft-data')(server.version)

server.on('login', function(client) {
  let loginPacket = mcData.loginPacket

  client.write('login', {
    entityId: client.id,
    isHardcore: false,
    gameMode: 0,
    previousGameMode: 255,
    worldNames: loginPacket.worldNames,
    dimensionCodec: loginPacket.dimensionCodec,
    dimension: loginPacket.dimension,
    worldName: 'minecraft:overworld',
    hashedSeed: [0, 0],
    maxPlayers: server.maxPlayers,
    viewDistance: 10,
    reducedDebugInfo: false,
    enableRespawnScreen: true,
    isDebug: false,
    isFlat: false
  });
  client.write('position', {
    x: 0,
    y: 1.62,
    z: 0,
    yaw: 0,
    pitch: 0,
    flags: 0x00
  });
});
```

## Expected behavior
Successfly connect

**Comment by dave-development** [comment]
I have the same problem.

**Comment by rom1504** [comment]
the problem is you send the packet incorrectly, check against the protocol definition
