### ISSUE TITLE
Disconnecting client because error Error: write ECONNRESET

### ISSUE THREAD

**Issue by lastuniverse** [PrismarineJS/node-minecraft-protocol#1240]
[+] The [FAQ](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - minecraft-protocol: 1.43.2
 - server: vanilla 1.20.1
 - client: oficial vanilla 1.20.1
 - node: 18.16.1

## Detailed description of a problem
If I connect to a vanilla local server via node-minecraft-protocol/tree/master/examples/proxy/proxy.js, then with any interaction with mobs I get Disconnecting client because error Error: write ECONNRESET

## Expected behavior
no disconnect

## Additional context
[packet logging in proxy](https://github.com/PrismarineJS/node-minecraft-protocol/files/12065332/log.txt)

error message in client
```
Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(7) + length(8) exceeds writerIndex(9): PooledUnsafeDirectByteBuf(ridx: 7, widx: 9, cap:9)
```

error message in proxy console
```
Disconnecting client because error Error: write ECONNRESET
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:930:11)
    at Socket._write (node:net:942:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Framer.ondata (/home/roman/work/minecraft_advanced_proxy/proxy/node_modules/readable-stream/lib/internal/streams/readable.js:662:22)
    at Framer.emit (node:events:513:28)
    at addChunk (/home/roman/work/minecraft_advanced_proxy/proxy/node_modules/readable-stream/lib/internal/streams/readable.js:278:12) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'write'
}
```

**Comment by lastuniverse** [comment]
there are still such disconnects immediately after entering a new server

```
Chunk size is 72 but only 47 was read ; partial packet : {"name":"world_particles","params":{"particleId":41,"longDistance":false,"x":-5945.852090802139,"y":-48.848546293937545,"z":297.4770044507851,"offsetX":0,"offsetY":0,"offsetZ":0,"particleData":0,"particles":1}}; buffer :262900c0b739da229f7069c0486c9d2a3acd48407297a1cf6b42b200000000000000000000000000000000000000010f6d696e6563726166743a626c6f636bfffa308000123fcb07
Chunk size is 72 but only 47 was read ; partial packet : {"name":"world_particles","params":{"particleId":41,"longDistance":false,"x":-5945.852090802139,"y":-48.848546293937545,"z":297.4770044507851,"offsetX":0,"offsetY":0,"offsetZ":0,"particleData":0,"particles":1}}; buffer :262900c0b739da229f7069c0486c9d2a3acd48407297a1cf6b42b200000000000000000000000000000000000000010f6d696e6563726166743a626c6f636bfffa308000123fcb07
Disconnecting client because error Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
```

**Comment by lastuniverse** [comment]
if kill all entities

```
/kill @e[type=!minecraft:player,distance=..15]
```
then no disconnect occurs.

**Comment by lastuniverse** [comment]
Thank you. Also, such a message periodically falls into the proxy console, after which a disconnect occurs, but without an error message
```
Chunk size is 63 but only 3 was read ; partial packet : {"name":"legacy_server_list_ping","params":{"payload":1}}; buffer :fe0101fa000b004d0043007c00500069006e00670048006f0073007400217f000d003100390032002e003100360038002e0031002e003100360033000063de
```
