### ISSUE TITLE
Get error when trying to write login data to client

### ISSUE THREAD

**Issue by LmanTW** [PrismarineJS/node-minecraft-protocol#1249]
## Full Error
```
Disconnecting client because error TypeError: Serialization error for play.toClient : SizeOf error for undefined : Cannot read properties of undefined (reading 'type')
    at nbt (eval at compile (/Users/lukelin/Desktop/LightServer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:110:24)
    at CompiledProtodef.sizeOf (/Users/lukelin/Desktop/LightServer/node_modules/protodef/src/compiler.js:89:14)
    at Object.sizeOfNbt [as nbt] (/Users/lukelin/Desktop/LightServer/node_modules/minecraft-protocol/src/datatypes/minecraft.js:55:20)
    at Object.packet_login (eval at compile (/Users/lukelin/Desktop/LightServer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:1338:24)
    at eval (eval at compile (/Users/lukelin/Desktop/LightServer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:2533:50)
    at packet (eval at compile (/Users/lukelin/Desktop/LightServer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:2600:9)
    at CompiledProtodef.sizeOf (/Users/lukelin/Desktop/LightServer/node_modules/protodef/src/compiler.js:89:14)
    at e.message (/Users/lukelin/Desktop/LightServer/node_modules/protodef/src/compiler.js:96:40)
    at tryCatch (/Users/lukelin/Desktop/LightServer/node_modules/protodef/src/utils.js:50:16)
    at CompiledProtodef.createPacketBuffer (/Users/lukelin/Desktop/LightServer/node_modules/protodef/src/compiler.js:96:20) {
  field: 'play.toClient'
}
```

## Versions
```
Node.js: v18.16.0
minecraft-protocol: 1.43.2
```

## Code
```js
const { createServer } = require('minecraft-protocol')

const server = createServer({
  'online-mode': true,
  encryption: true,

  version: '1.18.2',
  port: 25565,

  maxPlayers: 20,
  viewDistance: 10
})

server.on('login', (client) => {
  if (client.version !== server.version) {
    client.end(
      //error content
    )
  }

  client.write('login', {
    //data
  })
})
```

**Comment by IceBrick01** [comment]
笑死

**Comment by LmanTW** [comment]
thank you that help a log

**Comment by Ice-Brick** [comment]
笑死

**Comment by IceBrick01** [comment]
“log”

**Comment by BasToTheMax** [comment]
Any updates? Having the same issue

**Comment by Pandapip1** [comment]
Can repro.

**Comment by rom1504** [comment]
the error is saying you're sending the packet with data that does not make sense

**Comment by Pandapip1** [comment]
> the error is saying you're sending the packet with data that does not make sense

This was when running the example verbatim (except changing the version, obviously). This is definitely a bug.
