### ISSUE TITLE
support 1.20.2

### ISSUE THREAD

**Issue by lastuniverse** [PrismarineJS/node-minecraft-protocol#1258]
please add support for minecraft 1.20.2

**Comment by SilkePilon** [comment]
Support will be added once you implement it and open a Pull Request.

**Comment by lastuniverse** [comment]
It's a pity. If I succeed, I’ll definitely make a request

**Comment by kittenvr** [comment]
upvote

**Comment by Arthessia** [comment]
upvote here too :)

**Comment by lastuniverse** [comment]
Unfortunately, I won’t be able to deal with this issue for the next two weeks. It's a total mess at work.

**Comment by lastuniverse** [comment]
There is still a problem. Before updating node_minecraf_protocol to 1.20.2 you need to wait for the update https://github.com/PrismarineJS/minecraft-data

**Comment by lastuniverse** [comment]
I looked at https://github.com/PrismarineJS/minecraft-data .
Basically I'm not able to update minecraft-data without diving deep into it (((

**Comment by lastuniverse** [comment]
We are waiting for your reaction here https://github.com/PrismarineJS/minecraft-data/issues/779

**Comment by SuchBlue** [comment]
https://github.com/PrismarineJS/minecraft-data now supports 1.20.2

**Comment by SuchBlue** [comment]
I have created a pull request https://github.com/PrismarineJS/node-minecraft-protocol/pull/1261

**Comment by 7yl4r** [comment]
an example error when trying to connect:

```
(base) tylar@laptop:~/repos/mineflayer$ node examples/looker.js localhost 25565
TypeError: Serialization error for login.toServer : Write error for undefined : Cannot read properties of undefined (reading 'length')
    at module.exports.Write.UUID (/home/tylar/repos/mineflayer/node_modules/minecraft-protocol/src/datatypes/compiler-minecraft.js:50:25)
    at Object.packet_login_start (eval at compile (/home/tylar/repos/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:708:26)
    at eval (eval at compile (/home/tylar/repos/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:754:62)
    at packet (eval at compile (/home/tylar/repos/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:760:9)
    at CompiledProtodef.write (/home/tylar/repos/mineflayer/node_modules/protodef/src/compiler.js:76:12)
    at e.message (/home/tylar/repos/mineflayer/node_modules/protodef/src/compiler.js:102:25)
    at tryCatch (/home/tylar/repos/mineflayer/node_modules/protodef/src/utils.js:50:16)
    at CompiledProtodef.createPacketBuffer (/home/tylar/repos/mineflayer/node_modules/protodef/src/compiler.js:102:5)
    at Serializer.createPacketBuffer (/home/tylar/repos/mineflayer/node_modules/protodef/src/serializer.js:12:23)
    at Serializer._transform (/home/tylar/repos/mineflayer/node_modules/protodef/src/serializer.js:18:18) {
  field: 'login.toServer'
}
```

The [1.20.1 changelog](https://feedback.minecraft.net/hc/en-us/articles/19703470383757-Minecraft-Java-Edition-1-20-2) mentions "NETWORK PROTOCOL" changes. 
Without more details on that I don't know how to proceed.

**Comment by rom1504** [comment]
Check change in protocol.json in mcdata and also in wiki.vg/Protocol to
understand things
Notably configuration state was added

**Comment by Parker2991** [comment]
also happens in node-minecraft-protocol but something about the uuid
