### ISSUE TITLE
How can I login to a server with custom yggdrasil endpoint?

### ISSUE THREAD

**Issue by szdytom** [PrismarineJS/node-minecraft-protocol#1259]
[x] The [FAQ](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - minecraft-protocol: 1.44.0
 - server: vanilla 1.20.1 with [authlib-injector 1.2.3](https://github.com/yushijinhun/authlib-injector)
 - node: 20.8.0

## Detailed description of a problem

I have already set `authServer` and `sessionServer` correctly, and set `auth` to `"mojang"`. When I provide my `accessToken` and `clientToken`, the server disconnects by `unverified_username` error, when I provide my `password`, I got the following error:

```
TypeError [ERR_INVALID_ARG_TYPE]: Serialization error for login.toServer : SizeOf error for undefined : The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received undefined
    at new NodeError (node:internal/errors:406:5)
    at Function.byteLength (node:buffer:775:11)
    at Object.string (eval at compile (/home/szdytom/Documents/code/mc-bots/node_modules/protodef/src/compiler.js:258:12), <anonymous>:45:25)
    at Object.packet_login_start (eval at compile (/home/szdytom/Documents/code/mc-bots/node_modules/protodef/src/compiler.js:258:12), <anonymous>:665:27)
    at eval (eval at compile (/home/szdytom/Documents/code/mc-bots/node_modules/protodef/src/compiler.js:258:12), <anonymous>:713:62)
    at packet (eval at compile (/home/szdytom/Documents/code/mc-bots/node_modules/protodef/src/compiler.js:258:12), <anonymous>:718:9)
    at CompiledProtodef.sizeOf (/home/szdytom/Documents/code/mc-bots/node_modules/protodef/src/compiler.js:89:14)
    at e.message (/home/szdytom/Documents/code/mc-bots/node_modules/protodef/src/compiler.js:96:40)
    at tryCatch (/home/szdytom/Documents/code/mc-bots/node_modules/protodef/src/utils.js:50:16)
    at CompiledProtodef.createPacketBuffer (/home/szdytom/Documents/code/mc-bots/node_modules/protodef/src/compiler.js:96:20) {
  code: 'ERR_INVALID_ARG_TYPE',
  field: 'login.toServer'
}
```

## Current code
```js
const authlib = await import('./readConfig.js');
import mf from 'mineflayer';

let c = await authlib.readCredentials();
let t = await authlib.readTokens();
mf.createBot({
  host: '172.32.3.13',
  username: c.username,
  password: c.password,
  version: '1.20.1',
  authServer: c.endpoint + '/authserver',
  sessionServer: c.endpoint + '/sessionserver',
  auth: 'mojang',
});
```

## Expected behavior
Login to server.

## Additional context

The minecraft server and the yggdrasil server follows [this spec](https://github.com/yushijinhun/authlib-injector/wiki/Yggdrasil-%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%8A%80%E6%9C%AF%E8%A7%84%E8%8C%83)

Would anyone please explain how to use the custom `auth` function? I tried something like this, but I still does not work:

```js
let t = await authlib.readTokens();
let c = await authlib.readCredentials();
mf.createBot({
  host: '172.32.3.13',
  username: c.username,
  version: '1.20.1',
  authServer: c.endpoint + '/authserver',
  sessionServer: c.endpoint + '/sessionserver',
  auth: (client, options) => {
	  client.username = c.username;
	  client.session = t;
	  client.emit('session', t);
	  options.connect(client);
  },
});
```

**Comment by szdytom** [comment]
I solved the problem, I noticed I need to set `haveCredentials` to `true` as well. Thanks to your amazing library, but I think you should improve your document by a little as well.
