### ISSUE TITLE
versionChecking.js Bug

### ISSUE THREAD

**Issue by obseletecode72** [PrismarineJS/node-minecraft-protocol#1290]
[X] The [FAQ](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - minecraft-protocol: latest
 - server: paper 1.20.4
 - node: #.#.#

## Detailed description of a problem
just tried to join normally in the server and throwed an exception

## Expected behavior
join normally in the server

## Additional context
´´´
SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at Client.<anonymous> (C:\Users\Administrator\Desktop\mine\node_modules\minecraft-protocol\src\client\versionChecking.js:6:21)
    at Client.emit (node:events:526:35)
    at emitPacket (C:\Users\Administrator\Desktop\mine\node_modules\minecraft-protocol\src\client.js:83:12)
    at FullPacketParser.<anonymous> (C:\Users\Administrator\Desktop\mine\node_modules\minecraft-protocol\src\client.js:112:9)
    at FullPacketParser.emit (node:events:514:28)
    at addChunk (C:\Users\Administrator\Desktop\mine\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:279:12)
    at readableAddChunk (C:\Users\Administrator\Desktop\mine\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:262:11)
    at Readable.push (C:\Users\Administrator\Desktop\mine\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:228:10)
    at Transform.push (C:\Users\Administrator\Desktop\mine\node_modules\protodef\node_modules\readable-stream\lib\_stream_transform.js:132:32)
SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at Client.<anonymous> (C:\Users\Administrator\Desktop\mine\node_modules\minecraft-protocol\src\client\versionChecking.js:6:21)
    at Client.emit (node:events:526:35)
    at emitPacket (C:\Users\Administrator\Desktop\mine\node_modules\minecraft-protocol\src\client.js:83:12)
    at FullPacketParser.<anonymous> (C:\Users\Administrator\Desktop\mine\node_modules\minecraft-protocol\src\client.js:112:9)
    at FullPacketParser.emit (node:events:514:28)
    at addChunk (C:\Users\Administrator\Desktop\mine\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:279:12)
    at readableAddChunk (C:\Users\Administrator\Desktop\mine\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:262:11)
    at Readable.push (C:\Users\Administrator\Desktop\mine\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:228:10)
    at Transform.push (C:\Users\Administrator\Desktop\mine\node_modules\protodef\node_modules\readable-stream\lib\_stream_transform.js:132:32)
    ´´´

**Comment by wgaylord** [comment]
This is due to the disconect handler not being updated to handle 1.20.3+ NBT based disconnects in the Configuration and Play States.

**Comment by extremeheat** [comment]
Right, the underlying reason for this error is the server is kicking you (for one reason or another). It could be due to a version mismatch or something else.

Not sure what exactly the purpose of parsing the disconnect message really is beyond a formatted message, so we might be able to skip the parsing completely.

**Comment by wgaylord** [comment]
Pretty sure I fixed this inhttps://github.com/PrismarineJS/node-minecraft-protocol/pull/1291 but forgot to mention it here.

**Comment by Gjum** [comment]
This has not been part of any release, why was this closed already?
