### ISSUE TITLE
bad 1.20.5 slot types: The value of "offset" is out of range.

### ISSUE THREAD

**Issue by Vok1no** [PrismarineJS/node-minecraft-protocol#1348]
[ ] The [FAQ](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - minecraft-protocol: 1.50.0
 - server: vanilla/spigot/paper 1.21.1
 - node: 22.9.0

## Detailed description of a problem
A clear and concise description of what the problem is.
When the inventory is opened, this error pops up

RangeError [ERR_OUT_OF_RANGE]: Read error for undefined : The value of "offset" is out of range. It must be >= 0 and <= 37167. Received -1146269363
0|0 |     at boundsError (node:internal/buffer:88:9)
0|0 |     at Buffer.readUInt8 (node:internal/buffer:254:5)
0|0 |     at Object.readVarInt [as varint] (/home/botsServer/node_modules/minecraft-protocol/node_modules/protodef/src/datatypes/utils.js:68:22)
0|0 |     at Object.string (eval at compile (/home/botsServer/node_modules/minecraft-protocol/node_modules/protodef/src/compiler.js:262:12), <anonymous>:97:61)
0|0 |     at Object.BookPage (eval at compile (/home/botsServer/node_modules/minecraft-protocol/node_modules/protodef/src/compiler.js:262:12), <anonymous>:810:63)
0|0 |     at eval (eval at compile (/home/botsServer/node_modules/minecraft-protocol/node_modules/protodef/src/compiler.js:262:12), <anonymous>:439:44)
0|0 |     at eval (eval at compile (/home/botsServer/node_modules/minecraft-protocol/node_modules/protodef/src/compiler.js:262:12), <anonymous>:444:15)
0|0 |     at eval (eval at compile (/home/botsServer/node_modules/minecraft-protocol/node_modules/protodef/src/compiler.js:262:12), <anonymous>:447:13)
0|0 |     at Object.SlotComponent (eval at compile (/home/botsServer/node_modules/minecraft-protocol/node_modules/protodef/src/compiler.js:262:12), <anonymous>:729:9)
0|0 |     at eval (eval at compile (/home/botsServer/node_modules/minecraft-protocol/node_modules/protodef/src/compiler.js:262:12), <anonymous>:748:49) {
0|0 |   code: 'ERR_OUT_OF_RANGE',
0|0 |   field: 'play.toClient'
0|0 | }

## Current code
```js

```

**Comment by rom1504** [comment]
"vanilla/spigot/paper" which one?

**Comment by aeromechanic000** [comment]
is this issue solved?

**Comment by extremeheat** [comment]
Various SlotComponent issues were fixed in minecraft-data v3.109.1 with https://github.com/PrismarineJS/minecraft-data/pull/1173 and https://github.com/PrismarineJS/minecraft-data/pull/1155, please update your dependencies with `npm update` and check if the issue persists
