### ISSUE TITLE
Does node-minecraft-protocol work with spigot ?

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/node-minecraft-protocol#153]
I'm not getting any error but the bot doesn't actually show on on the server.
I'm getting that in the console (trying client_echo.js) : 
```
MC-PROTO: 13601 Old-styling packet
MC-PROTO: 13601 writing packetId handshaking.set_protocol (0x0)
MC-PROTO: 13601 { protocolVersion: 47,
  serverHost: 'localhost',
  serverPort: 25565,
  nextState: 2 }
MC-PROTO: 13601 Old-styling packet
MC-PROTO: 13601 writing packetId login.login_start (0x0)
MC-PROTO: 13601 { username: 'bot' }
connected
MC-PROTO: 13601 read packetId login.compress (0x3)
MC-PROTO: 13601 { id: 3, state: 'login', threshold: 256 }
MC-PROTO: 13601 read packetId login.success (0x2)
MC-PROTO: 13601 { id: 2,
  state: 'login',
  uuid: '67128b5b-2e6b-3ad1-baa0-1b937b03e5c5',
  username: 'bot' }
```

the bot isn't showing in tab, not possible to /tp to him,...

**Comment by roblabla** [comment]
I'll take a look. It should.

**Comment by rom1504** [comment]
I was trying on the wrong server address.... So it works actually...

**Comment by rom1504** [comment]
ok so apparently @roblabla changed his server from spigot to vanilla. So spigot probably doesn't work.

**Comment by zuazo** [comment]
The JSON message returned by spigot is not parsed correctly:

```json
{ extra: [ { color: 'yellow', text: 'bot1 joined the game' } ], text: '' }
{ extra: [ '<user1> hello' ], text: '' }
```

But this particular example (`client_echo`) seems not to work well even in vanilla:

```
MC-PROTO: 20017 Old-styling packet
MC-PROTO: 20017 writing packetId handshaking.set_protocol (0x0)
MC-PROTO: 20017 { protocolVersion: 47,
  serverHost: 'localhost',
  serverPort: 25565,
  nextState: 2 }
MC-PROTO: 20017 Old-styling packet
MC-PROTO: 20017 writing packetId login.login_start (0x0)
MC-PROTO: 20017 { username: 'bot1' }
connected
MC-PROTO: 20017 read packetId login.compress (0x3)
MC-PROTO: 20017 { id: 3, state: 'login', threshold: 256 }
MC-PROTO: 20017 read packetId login.success (0x2)
MC-PROTO: 20017 { id: 2,
  state: 'login',
  uuid: '05f673da-66b5-37e3-b03b-09bbf434403e',
  username: 'bot1' }
MC-PROTO: 20017 read packetId play.keep_alive (0x0)
MC-PROTO: 20017 { id: 0, state: 'play', keepAliveId: 76197938 }
MC-PROTO: 20017 New-styling packet
MC-PROTO: 20017 writing packetId play.keep_alive (0x0)
MC-PROTO: 20017 { keepAliveId: 76197938 }
MC-PROTO: 20017 read packetId play.keep_alive (0x0)
MC-PROTO: 20017 { id: 0, state: 'play', keepAliveId: 76199987 }
MC-PROTO: 20017 New-styling packet
MC-PROTO: 20017 writing packetId play.keep_alive (0x0)
MC-PROTO: 20017 { keepAliveId: 76199987 }
MC-PROTO: 20017 read packetId play.chat (0x2)
MC-PROTO: 20017 { id: 2,
  state: 'play',
  message: '{"translate":"chat.type.text","with":[{"insertion":"user1","clickEvent":{"action":"suggest_command","value":"/msg user1 "},"hoverEvent":{"action":"show_entity","value":"{id:\\"c5b6c7df-55c8-32cb-a9a8-8e2857362445\\",name:\\"user1\\"}"},"text":"user1"},"hello"]}',
  position: 0 }
MC-PROTO: 20017 New-styling packet
MC-PROTO: 20017 writing packetId play.chat (0x1)
MC-PROTO: 20017 { message: 'hello' }
MC-PROTO: 20017 read packetId play.chat (0x2)
MC-PROTO: 20017 { id: 2,
  state: 'play',
  message: '{"translate":"chat.type.text","with":[{"insertion":"bot1","clickEvent":{"action":"suggest_command","value":"/msg bot1 "},"hoverEvent":{"action":"show_entity","value":"{id:\\"05f673da-66b5-37e3-b03b-09bbf434403e\\",name:\\"bot1\\"}"},"text":"bot1"},"hello"]}',
  position: 0 }
MC-PROTO: 20017 New-styling packet
MC-PROTO: 20017 writing packetId play.chat (0x1)
MC-PROTO: 20017 { message: 'hello' }
MC-PROTO: 20017 read packetId play.chat (0x2)
MC-PROTO: 20017 { id: 2,
  state: 'play',
  message: '{"translate":"chat.type.text","with":[{"insertion":"bot1","clickEvent":{"action":"suggest_command","value":"/msg bot1 "},"hoverEvent":{"action":"show_entity","value":"{id:\\"05f673da-66b5-37e3-b03b-09bbf434403e\\",name:\\"bot1\\"}"},"text":"bot1"},"hello"]}',
  position: 0 }
MC-PROTO: 20017 New-styling packet
MC-PROTO: 20017 writing packetId play.chat (0x1)
MC-PROTO: 20017 { message: 'hello' }
MC-PROTO: 20017 read packetId play.chat (0x2)
MC-PROTO: 20017 { id: 2,
  state: 'play',
  message: '{"translate":"chat.type.text","with":[{"insertion":"bot1","clickEvent":{"action":"suggest_command","value":"/msg bot1 "},"hoverEvent":{"action":"show_entity","value":"{id:\\"05f673da-66b5-37e3-b03b-09bbf434403e\\",name:\\"bot1\\"}"},"text":"bot1"},"hello"]}',
  position: 0 }
MC-PROTO: 20017 New-styling packet
MC-PROTO: 20017 writing packetId play.chat (0x1)
MC-PROTO: 20017 { message: 'hello' }
MC-PROTO: 20017 read packetId play.chat (0x2)
MC-PROTO: 20017 { id: 2,
  state: 'play',
  message: '{"translate":"chat.type.text","with":[{"insertion":"bot1","clickEvent":{"action":"suggest_command","value":"/msg bot1 "},"hoverEvent":{"action":"show_entity","value":"{id:\\"05f673da-66b5-37e3-b03b-09bbf434403e\\",name:\\"bot1\\"}"},"text":"bot1"},"hello"]}',
  position: 0 }
MC-PROTO: 20017 New-styling packet
MC-PROTO: 20017 writing packetId play.chat (0x1)
MC-PROTO: 20017 { message: 'hello' }
MC-PROTO: 20017 read packetId play.chat (0x2)
MC-PROTO: 20017 { id: 2,
  state: 'play',
  message: '{"translate":"chat.type.text","with":[{"insertion":"bot1","clickEvent":{"action":"suggest_command","value":"/msg bot1 "},"hoverEvent":{"action":"show_entity","value":"{id:\\"05f673da-66b5-37e3-b03b-09bbf434403e\\",name:\\"bot1\\"}"},"text":"bot1"},"hello"]}',
  position: 0 }
MC-PROTO: 20017 New-styling packet
MC-PROTO: 20017 writing packetId play.chat (0x1)
MC-PROTO: 20017 { message: 'hello' }
MC-PROTO: 20017 read packetId play.chat (0x2)
MC-PROTO: 20017 { id: 2,
  state: 'play',
  message: '{"translate":"chat.type.text","with":[{"insertion":"bot1","clickEvent":{"action":"suggest_command","value":"/msg bot1 "},"hoverEvent":{"action":"show_entity","value":"{id:\\"05f673da-66b5-37e3-b03b-09bbf434403e\\",name:\\"bot1\\"}"},"text":"bot1"},"hello"]}',
  position: 0 }
MC-PROTO: 20017 New-styling packet
MC-PROTO: 20017 writing packetId play.chat (0x1)
MC-PROTO: 20017 { message: 'hello' }
MC-PROTO: 20017 read packetId play.chat (0x2)
MC-PROTO: 20017 { id: 2,
  state: 'play',
  message: '{"translate":"chat.type.text","with":[{"insertion":"bot1","clickEvent":{"action":"suggest_command","value":"/msg bot1 "},"hoverEvent":{"action":"show_entity","value":"{id:\\"05f673da-66b5-37e3-b03b-09bbf434403e\\",name:\\"bot1\\"}"},"text":"bot1"},"hello"]}',
  position: 0 }
MC-PROTO: 20017 New-styling packet
MC-PROTO: 20017 writing packetId play.chat (0x1)
MC-PROTO: 20017 { message: 'hello' }
MC-PROTO: 20017 read packetId play.chat (0x2)
MC-PROTO: 20017 { id: 2,
  state: 'play',
  message: '{"translate":"chat.type.text","with":[{"insertion":"bot1","clickEvent":{"action":"suggest_command","value":"/msg bot1 "},"hoverEvent":{"action":"show_entity","value":"{id:\\"05f673da-66b5-37e3-b03b-09bbf434403e\\",name:\\"bot1\\"}"},"text":"bot1"},"hello"]}',
  position: 0 }
MC-PROTO: 20017 New-styling packet
MC-PROTO: 20017 writing packetId play.chat (0x1)
MC-PROTO: 20017 { message: 'hello' }
MC-PROTO: 20017 read packetId play.chat (0x2)
MC-PROTO: 20017 { id: 2,
  state: 'play',
  message: '{"translate":"chat.type.text","with":[{"insertion":"bot1","clickEvent":{"action":"suggest_command","value":"/msg bot1 "},"hoverEvent":{"action":"show_entity","value":"{id:\\"05f673da-66b5-37e3-b03b-09bbf434403e\\",name:\\"bot1\\"}"},"text":"bot1"},"hello"]}',
  position: 0 }
MC-PROTO: 20017 New-styling packet
MC-PROTO: 20017 writing packetId play.chat (0x1)
MC-PROTO: 20017 { message: 'hello' }
MC-PROTO: 20017 read packetId play.chat (0x2)
MC-PROTO: 20017 { id: 2,
  state: 'play',
  message: '{"translate":"chat.type.text","with":[{"insertion":"bot1","clickEvent":{"action":"suggest_command","value":"/msg bot1 "},"hoverEvent":{"action":"show_entity","value":"{id:\\"05f673da-66b5-37e3-b03b-09bbf434403e\\",name:\\"bot1\\"}"},"text":"bot1"},"hello"]}',
  position: 0 }
MC-PROTO: 20017 New-styling packet
MC-PROTO: 20017 writing packetId play.chat (0x1)
MC-PROTO: 20017 { message: 'hello' }
MC-PROTO: 20017 read packetId play.chat (0x2)
MC-PROTO: 20017 { id: 2,
  state: 'play',
  message: '{"translate":"chat.type.text","with":[{"insertion":"bot1","clickEvent":{"action":"suggest_command","value":"/msg bot1 "},"hoverEvent":{"action":"show_entity","value":"{id:\\"05f673da-66b5-37e3-b03b-09bbf434403e\\",name:\\"bot1\\"}"},"text":"bot1"},"hello"]}',
  position: 0 }
MC-PROTO: 20017 New-styling packet
MC-PROTO: 20017 writing packetId play.chat (0x1)
MC-PROTO: 20017 { message: 'hello' }

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:275:12)
    at finishWriting (/home/yunweb/src/node-minecraft-protocol/dist/client.js:192:17)
    at newStylePacket (/home/yunweb/src/node-minecraft-protocol/dist/protocol.js:988:3)
    at Client.write (/home/yunweb/src/node-minecraft-protocol/dist/client.js:202:5)
    at Client.<anonymous> (/home/yunweb/src/node-minecraft-protocol/examples/client_echo/client_echo.js:17:12)
    at Client.emit (events.js:95:17)
    at afterParse (/home/yunweb/src/node-minecraft-protocol/dist/client.js:99:10)
    at /home/yunweb/src/node-minecraft-protocol/dist/protocol.js:1076:9
    at Inflate.onEnd (zlib.js:166:5)
    at Inflate.emit (events.js:117:20)
```

All tested with the current master.

**Comment by rom1504** [comment]
So : yeah client_echo chat parsing doesn't work, not surprising, parsing chat is a bit complicated now, even mineflayer doesn't parse all kind of chat yet. ( #154 )

But thanks to recent commits to fix proxy on us.mineplex.com, spigot now seems fixed (bot correctly spawn and it can be seen in tab)
