### ISSUE TITLE
Uncaught TypeError when particles emit from players' feet when hitting ground

### ISSUE THREAD

**Issue by tsolace** [PrismarineJS/node-minecraft-protocol#395]
My player hits the ground jumping from 3 blocks or higher, and particles emit from the bottom of his feet. Specifically this particle emission crashes the bot, none of the other ones (block breaking, sprinting) do.
```
[white@hpe minebots]$ node minebot.js
/home/white/Programs/minebots/node_modules/mineflayer/node_modules/minecraft-protocol/dist/transforms/framing.js:113
          } else throw e;
                 ^

TypeError: Deserialization error for play.toClient.world_particles.data : Read error for params.world_particles.data : countField.split is not a function
    at getField (/home/white/Programs/minebots/node_modules/mineflayer/node_modules/protodef/dist/utils.js:10:34)
    at ProtoDef.readArray (/home/white/Programs/minebots/node_modules/mineflayer/node_modules/protodef/dist/datatypes/structures.js:28:87)
    at ProtoDef.read (/home/white/Programs/minebots/node_modules/mineflayer/node_modules/protodef/dist/protodef.js:102:31)
    at /home/white/Programs/minebots/node_modules/mineflayer/node_modules/protodef/dist/datatypes/structures.js:108:32
    at tryCatch (/home/white/Programs/minebots/node_modules/mineflayer/node_modules/protodef/dist/utils.js:33:12)
    at tryDoc (/home/white/Programs/minebots/node_modules/mineflayer/node_modules/protodef/dist/utils.js:40:10)
    at /home/white/Programs/minebots/node_modules/mineflayer/node_modules/protodef/dist/datatypes/structures.js:107:5
    at Array.forEach (native)
    at ProtoDef.readContainer (/home/white/Programs/minebots/node_modules/mineflayer/node_modules/protodef/dist/datatypes/structures.js:102:12)
    at ProtoDef.read (/home/white/Programs/minebots/node_modules/mineflayer/node_modules/protodef/dist/protodef.js:46:25)
```

**Comment by rom1504** [comment]
Run npm update, your Minecraft-data package is outdated.
