### ISSUE TITLE
Connection through BungeeCord/Waterfall forcibly closed

### ISSUE THREAD

**Issue by rockmacaca** [PrismarineJS/node-minecraft-protocol#432]
Can we update the minecraft-data dependency to 2.7.0 to support the newer minecraft versions?

**Comment by rom1504** [comment]
just run `npm update`. It's a `^` dependency.

**Comment by rockmacaca** [comment]
Sorry, I was a bit hasty there, it works fine now with vanilla and Forge 1.10.2.

I just discovered this, so I'm still trying to figure out the compatibility status with things. It doesn't seem to work with SpongeVanilla or through Bungee/Waterfall? Is this normal?

**Comment by roblabla** [comment]
It should work with 1.10. What doesn't work ? Do you have an error or somth ?

**Comment by rockmacaca** [comment]
Everything I'm using is based on 1.10.2 -

What works:
* Vanilla 1.10.2
* Forge Universal (no mods)
* Paper/Spigot (and I assume Bukkit)

What doesn't work
* Anything behind a BungeeCord proxy
* SpongeVanilla

**Comment by rom1504** [comment]
And what error do you get node-minecraft-protocol side ? (maybe try enable the debug mode with `DEBUG="minecraft-protocol"`)

**Comment by rockmacaca** [comment]
No errors, actually, it seems to just drop and exit:

```
  minecraft-protocol writing packet handshaking.set_protocol +0ms
  minecraft-protocol { protocolVersion: 210, serverHost: 'localhost', serverPort: 25565, nextState: 2 } +0ms
  minecraft-protocol writing packet login.login_start +15ms
  minecraft-protocol { username: 'IamaBot' } +0ms
  minecraft-protocol read packet login.compress +0ms
  minecraft-protocol { threshold: 256 } +0ms
  minecraft-protocol read packet login.success +16ms
  minecraft-protocol { uuid: '37a63bc4-932a-3040-a587-6df93c2c1c5e', username: 'IamaBot' } +0ms
  minecraft-protocol read packet play.custom_payload +0ms
  minecraft-protocol { channel: 'REGISTER', data: <Buffer 46 4d 4c 00 46 4d 4c 7c 48 53 00 46 4f 52 47 45 00 42 75 6e 67 65 65 43 6f 72 64> } +0ms
```

**Comment by rockmacaca** [comment]
So, the issue I'm most interested in getting fixed is Bungeecord/Waterfall. The setup I'm trying out that isn't behaving right is

1. BungeeCord/Waterfall with `ip_forward` set to either true or false, on port 25565
2. Vanilla 1.10.2 running on port 25566

My Minecraft client connects fine on either port, but when my script connects through BungeeCord on 25565, it get disconnected with the event

```
[Server thread/INFO]: IamaBot lost connection: TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}```

**Comment by rockmacaca** [comment]
I'm just following along with what you opened in #433, looks like this is where it rejects the packet and closes the connection?

```
break in C:\Users\kherock\Desktop\mc\node_modules\minecraft-protocol\dist\client\pluginChannels.js:49
 47     if (channel) {
 48       debugger;
>49       debug(proto.parsePacketBuffer(channel, packet.data));
 50       if (proto.types[channel]) packet.data = proto.parsePacketBuffer(channel, packet.data).data;
 51       client.emit(channel, packet.data);
n
break in C:\Users\kherock\Desktop\mc\node_modules\minecraft-protocol\dist\transforms\framing.js:111
 109           error = _readVarInt2.error;
 110         } catch (e) {
>111           if (e.partialReadError) {
 112             break;
 113           } else throw e;
debug> repl
Press Ctrl + C to leave debug repl
> console.trace()
< Trace
<     at eval (eval at _transform (C:\Users\kherock\Desktop\mc\node_modules\minecraft-protocol\dist\transforms\framing.js:111:11), <anonymous>:1:9)
<     at Splitter._transform (C:\Users\kherock\Desktop\mc\node_modules\minecraft-protocol\dist\transforms\framing.js:111:11)
<     at Splitter.Transform._read (C:\Users\kherock\Desktop\mc\node_modules\readable-stream\lib\_stream_transform.js:159:10)
<     at Splitter.Transform._write (C:\Users\kherock\Desktop\mc\node_modules\readable-stream\lib\_stream_transform.js:147:83)
<     at doWrite (C:\Users\kherock\Desktop\mc\node_modules\readable-stream\lib\_stream_writable.js:319:64)
<     at writeOrBuffer (C:\Users\kherock\Desktop\mc\node_modules\readable-stream\lib\_stream_writable.js:308:5)
<     at Splitter.Writable.write (C:\Users\kherock\Desktop\mc\node_modules\readable-stream\lib\_stream_writable.js:246:11)
<     at Socket.ondata (_stream_readable.js:556:20)
<     at emitOne (events.js:96:13)
<     at Socket.emit (events.js:188:7)
> e
{ handle: 16,
  type: 'error',
  className: 'Error',
  constructorFunction: { ref: 17 },
  protoObject: { ref: 18 },
  prototypeObject: { ref: 3 },
  properties:
   [ { name: 'stack', attributes: 2, propertyType: 3, ref: 3 },
     { name: 'message', attributes: 2, propertyType: 0, ref: 19 },
     { name: 'name', propertyType: 0, ref: 20 },
     { name: 'partialReadError', propertyType: 0, ref: 21 } ],
  text: 'Error: Read error for undefined : Missing characters in string, found size is 27 expected size was 71' }
```

**Comment by rockmacaca** [comment]
Interestingly, just surrounding the attempt to decode the packet in a try/catch seems to make everything work correctly!?

```
/* pluginChannels.js */

function onCustomPayload(packet) {
  var channel = channels.find(function (channel) {
    return channel === packet.channel;
  });
  debug(packet.data.toString()); // 'FML FML|HS FORGE BungeeCord'
  if (channel) {
    try {
      if (proto.types[channel]) packet.data = proto.parsePacketBuffer(channel, packet.data).data;
    } catch (e) {
      console.log(e);
    }
    client.emit(channel, packet.data);
  }
}
```

**Comment by rockmacaca** [comment]
So if I'm understanding what's happening here, calling `parsePacketBuffer` for the `REGISTER` type attempts to decode the buffer by looking at the MSB and using that to determine what the size of the message will be? For the packet from BungeeCord, it's just a plain UTF-8 string, and that seems to trip up ProtoDef.

**Comment by rockmacaca** [comment]
Let me know if there's anything fundamentally wrong here using the below as a fix:

```
/* pluginChannels.js */

function onCustomPayload(packet) {
  var channel = channels.find(function (channel) {
    return channel === packet.channel;
  });
  if (channel) {
    if (proto.types[channel]) try {
      packet.data = proto.parsePacketBuffer(channel, packet.data).data;
    } catch (e) {
      packet.data = packet.data.toString();
    }
    client.emit(channel, packet.data);
  }
}
```

**Comment by roblabla** [comment]
If we don't know the channel, we shouldn't try to convert it to a string (many mods send data as a byte array).

Anyway, it looks like this means there's either an error in BungeeCord or in the way we treat REGISTER.

**Comment by roblabla** [comment]
Welp, I get it. "payload is a null-separated list of strings". https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/client/pluginChannels.js#L14

**Comment by roblabla** [comment]
@rockmacaca can you try #434 and tell me if it fixes your problem ?
