### ISSUE TITLE
Socks proxy support error

### ISSUE THREAD

**Issue by hisdudeness1** [PrismarineJS/node-minecraft-protocol#436]
So, i tried to make mc-proto work with socks proxy server. I started local socksv5 proxy, grabbed proxy.js from examples and changed properties on targetClient from this: 

``` js
var targetClient = mc.createClient({
    host: host,
    port: port,
    username: client.username,
    keepAlive:false,
    version:version
});
```

to this:

``` js
var targetClient = mc.createClient({
    stream: socks.createConnection({
      host: host,
      port: port
    }),
    username: client.username,
    keepAlive:false,
    version:version
  });
```

Mcproxy starts with no errors, but when im trying connect to it via vanilla client, i get error:

```
Incoming connection (127.0.0.1)
Connection error by server (127.0.0.1)  { [Error: Deserialization error for handshaking.toClient : Read error for name : 0 is not in the mappings value]
  field: 'handshaking.toClient',
  buffer: <Buffer 00 05 00 00 01> }
Error: Deserialization error for handshaking.toClient : Read error for name : 0 is not in the mappings value
    at ProtoDef.readMapper (/home/user/proxy/node_modules/minecraft-protocol/node_modules/protodef/dist/datatypes/utils.js:43:34)
    at ProtoDef.read (/home/user/proxy/node_modules/minecraft-protocol/node_modules/protodef/dist/protodef.js:102:31)
    at /home/user/proxy/node_modules/minecraft-protocol/node_modules/protodef/dist/datatypes/structures.js:85:32
    at tryCatch (/home/user/proxy/node_modules/minecraft-protocol/node_modules/protodef/dist/utils.js:83:12)
    at tryDoc (/home/user/proxy/node_modules/minecraft-protocol/node_modules/protodef/dist/utils.js:90:10)
    at /home/user/proxy/node_modules/minecraft-protocol/node_modules/protodef/dist/datatypes/structures.js:84:5
    at Array.forEach (native)
    at ProtoDef.readContainer (/home/user/proxy/node_modules/minecraft-protocol/node_modules/protodef/dist/datatypes/structures.js:79:12)
    at ProtoDef.read (/home/user/proxy/node_modules/minecraft-protocol/node_modules/protodef/dist/protodef.js:46:25)
    at ProtoDef.read (/home/user/proxy/node_modules/minecraft-protocol/node_modules/protodef/dist/protodef.js:102:31)
Connection closed by client (127.0.0.1)
```

I found similar error [here](http://www.gitterforum.com/discussion/prismarinejs-node-minecraft-protocol?page=3811)

Help?

**Comment by roblabla** [comment]
Fixed your comment for you :)

**Comment by rom1504** [comment]
it seems you are missing some parameters (socksHost and socksPort) to create the sock stream, see https://github.com/PrismarineJS/node-minecraft-protocol/issues/185#issuecomment-254785390

**Comment by hisdudeness1** [comment]
If sockshost\port not defined it puts default localhost:1080, dont it?

**Comment by hisdudeness1** [comment]
```js
var targetClient = mc.createClient({
    stream: socks.createConnection({
      host: host,
      port: port,
      socksHost: 'localhost',
      socksPort: 1080
    }),
    username: client.username,
    keepAlive:false,
    version:version
  });
```
still same error
