### ISSUE TITLE
Deserialization error for handshaking.toServer

### ISSUE THREAD

**Issue by mai1015** [PrismarineJS/node-minecraft-protocol#440]
It was working fine. 
but after i use darkbot to test the server, i fail to use my normal client to get motd.
Why is this happening?

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Deserialization error for handshaking.toServer : Read error for name : 122 is not in the mappings value
    at ProtoDef.readMapper (/Users/mai1015/Documents/Programming/Nodejs/project/bungee/node_modules/minecraft-protocol/node_modules/protodef/dist/datatypes/utils.js:43:34)
    at ProtoDef.read (/Users/mai1015/Documents/Programming/Nodejs/project/bungee/node_modules/minecraft-protocol/node_modules/protodef/dist/protodef.js:102:31)
    at /Users/mai1015/Documents/Programming/Nodejs/project/bungee/node_modules/minecraft-protocol/node_modules/protodef/dist/datatypes/structures.js:85:32
    at tryCatch (/Users/mai1015/Documents/Programming/Nodejs/project/bungee/node_modules/minecraft-protocol/node_modules/protodef/dist/utils.js:83:12)
    at tryDoc (/Users/mai1015/Documents/Programming/Nodejs/project/bungee/node_modules/minecraft-protocol/node_modules/protodef/dist/utils.js:90:10)
    at /Users/mai1015/Documents/Programming/Nodejs/project/bungee/node_modules/minecraft-protocol/node_modules/protodef/dist/datatypes/structures.js:84:5
    at Array.forEach (native)
    at ProtoDef.readContainer (/Users/mai1015/Documents/Programming/Nodejs/project/bungee/node_modules/minecraft-protocol/node_modules/protodef/dist/datatypes/structures.js:79:12)
    at ProtoDef.read (/Users/mai1015/Documents/Programming/Nodejs/project/bungee/node_modules/minecraft-protocol/node_modules/protodef/dist/protodef.js:46:25)
    at ProtoDef.read (/Users/mai1015/Documents/Programming/Nodejs/project/bungee/node_modules/minecraft-protocol/node_modules/protodef/dist/protodef.js:102:31)
    at e.message (/Users/mai1015/Documents/Programming/Nodejs/project/bungee/node_modules/minecraft-protocol/node_modules/protodef/dist/protodef.js:160:23)
    at tryCatch (/Users/mai1015/Documents/Programming/Nodejs/project/bungee/node_modules/minecraft-protocol/node_modules/protodef/dist/utils.js:83:12)
    at ProtoDef.parsePacketBuffer (/Users/mai1015/Documents/Programming/Nodejs/project/bungee/node_modules/minecraft-protocol/node_modules/protodef/dist/protodef.js:159:23)
    at Parser.parsePacketBuffer (/Users/mai1015/Documents/Programming/Nodejs/project/bungee/node_modules/minecraft-protocol/node_modules/protodef/dist/serializer.js:70:25)
    at Parser._transform (/Users/mai1015/Documents/Programming/Nodejs/project/bungee/node_modules/minecraft-protocol/node_modules/protodef/dist/serializer.js:79:25)
    at Parser.Transform._read (/Users/mai1015/Documents/Programming/Nodejs/project/bungee/node_modules/minecraft-protocol/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at Parser.Transform._write (/Users/mai1015/Documents/Programming/Nodejs/project/bungee/node_modules/minecraft-protocol/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Users/mai1015/Documents/Programming/Nodejs/project/bungee/node_modules/minecraft-protocol/node_modules/readable-stream/lib/_stream_writable.js:319:64)
    at writeOrBuffer (/Users/mai1015/Documents/Programming/Nodejs/project/bungee/node_modules/minecraft-protocol/node_modules/readable-stream/lib/_stream_writable.js:308:5)
```

this is how i am creating my server
```javascript
var server = mc.createServer({
        'online-mode': config.onlineMode,   // optional
        encryption: true,      // optional
        host: '0.0.0.0',       // optional
        port: config.port,           // optional
        version: config.version,
        kickTimeout: config.kickTimeout,
    });
```

**Comment by mai1015** [comment]
Oh, i changed playercount in server...
this is the cause of the problem but why?

**Comment by ansabd** [comment]
I am having same problem what should I do can anyone help me!!!
