### ISSUE TITLE
[BungeeCord] 1.11.2 Support doesn't seem to work?

### ISSUE THREAD

**Issue by tmfksoft** [PrismarineJS/node-minecraft-protocol#464]
I've tried using your out of the box example in the readme to connect to my 1.11.2 server running BungeeCord and Paper.

However BungeeCord kicks the client for not being 1.11.2, Is there something I'm missing?

**Comment by tmfksoft** [comment]
Edit to that, It appears specifying the client version in options works (I dug through the code to find that though)

However now I can't connect due to this:

/home/thomas/mc_bot/node_modules/minecraft-protocol/dist/transforms/framing.js:112
          } else throw e;
                 ^

Error: Deserialization error for play.toClient : Read error for name : 84 is not in the mappings value
    at ProtoDef.readMapper (/home/thomas/mc_bot/node_modules/protodef/dist/datatypes/utils.js:43:34)
    at ProtoDef.read (/home/thomas/mc_bot/node_modules/protodef/dist/protodef.js:102:31)
    at /home/thomas/mc_bot/node_modules/protodef/dist/datatypes/structures.js:85:32
    at tryCatch (/home/thomas/mc_bot/node_modules/protodef/dist/utils.js:83:12)
    at tryDoc (/home/thomas/mc_bot/node_modules/protodef/dist/utils.js:90:10)
    at /home/thomas/mc_bot/node_modules/protodef/dist/datatypes/structures.js:84:5
    at Array.forEach (native)
    at ProtoDef.readContainer (/home/thomas/mc_bot/node_modules/protodef/dist/datatypes/structures.js:79:12)
    at ProtoDef.read (/home/thomas/mc_bot/node_modules/protodef/dist/protodef.js:46:25)
    at ProtoDef.read (/home/thomas/mc_bot/node_modules/protodef/dist/protodef.js:102:31)

**Comment by rom1504** [comment]
Is 0x54 (==84) a custom packet of bungeecord/paper ?

**Comment by tmfksoft** [comment]
Just asked the devs of both, they insist its nothing core to bungeecord or paper (Spigot fork).
Is there a way I can probe at it and figure out what it is?

**Comment by roblabla** [comment]
@tmfksoft You can enable DEBUG. That will print the packets to the console. With this, we might be able to pinpoint where the problem is. To do this, when you start the client, put the DEBUG environment variable to `minecraft-protocol`.

**Comment by tmfksoft** [comment]
Gets as far as here:

  minecraft-protocol { effectId: 578635009,
  minecraft-protocol   location: { x: 6155401, y: -743, z: 24671266 },
  minecraft-protocol   data: 975356583,
  minecraft-protocol   global: true } +0ms
events.js:160
      throw er; // Unhandled 'error' event
      ^

Nothing else past it.

**Comment by roblabla** [comment]
@tmfksoft could you gist/pastebin the entire thing ?

**Comment by tmfksoft** [comment]
Hope this helps :P
http://paste.ubuntu.com/23890877/

**Comment by rom1504** [comment]
same 84 here https://github.com/PrismarineJS/node-minecraft-protocol/issues/464

**Comment by ryoid** [comment]
Getting this error when connecting to cosmicpvp.com. Tried specifying the version to a lower number (1.9), but getting a `unexpected end of file` instead. Might be related to #462

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/node-minecraft-protocol/issues/336

**Comment by rom1504** [comment]
please reopen if you still see this
