### ISSUE TITLE
Crash when client running wrong MC version opens server list

### ISSUE THREAD

**Issue by echo35** [PrismarineJS/node-minecraft-protocol#466]
I'm running [server_helloworld.js](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/examples/server_helloworld/server_helloworld.js).

```
$ node server_helloworld.js
Server listening on port 25565
```

So long as I run my client under Minecraft 1.8, I can ping the server and it works fine:
![screenshot_1.8](http://i.imgur.com/9fo9DZR.png)

The problem occurs when a client running any other version of the game opens the multiplayer menu (e.g. 1.11.2):
![screenshot_1.11.2](http://i.imgur.com/dzJtAeB.png)

In the terminal:
```
$ node server_helloworld.js
Server listening on port 25565
events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: Deserialization error for handshaking.toServer : Read error for name : 122 is not in the mappings value
    at ProtoDef.readMapper (<redacted>/NodeJS/minecraft/node_modules/protodef/dist/datatypes/utils.js:43:34)
    at ProtoDef.read (<redacted>/NodeJS/minecraft/node_modules/protodef/dist/protodef.js:102:31)
    at <redacted>/NodeJS/minecraft/node_modules/protodef/dist/datatypes/structures.js:85:32
    at tryCatch (<redacted>/NodeJS/minecraft/node_modules/protodef/dist/utils.js:83:12)
    at tryDoc (<redacted>/NodeJS/minecraft/node_modules/protodef/dist/utils.js:90:10)
    at <redacted>/NodeJS/minecraft/node_modules/protodef/dist/datatypes/structures.js:84:5
    at Array.forEach (native)
    at ProtoDef.readContainer (<redacted>/NodeJS/minecraft/node_modules/protodef/dist/datatypes/structures.js:79:12)
    at ProtoDef.read (<redacted>/NodeJS/minecraft/node_modules/protodef/dist/protodef.js:46:25)
    at ProtoDef.read (<redacted>/NodeJS/minecraft/node_modules/protodef/dist/protodef.js:102:31)
```

From the looks of it, [server_helloworld.js](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/examples/server_helloworld/server_helloworld.js) already has error handling implemented, but it hasn't actually caught this error.

The big issue is no server admin can guarantee players will always be running the same version of the game when logging in to other servers, and any client simply opening the server list triggers a crash. 

Thanks in advance for any help or assistance figuring this out.

**Comment by rom1504** [comment]
see #463
