### ISSUE TITLE
Pinging with the wrong version crashes the server

### ISSUE THREAD

**Issue by InventivetalentDev** [PrismarineJS/node-minecraft-protocol#469]
Trying to ping the server from a Minecraft version different from the one specified in `createServer` (e.g. 1.11.2 -> 1.11, 1.11 -> 1.10, ...) results in a crash:
```
Error: Deserialization error for handshaking.toServer : Read error for name : 122 is not in the mappings value
    at ProtoDef.readMapper (D:\_Projects_Node\mcauth-server\node_modules\minecraft-protocol\node_modules\protodef\dist\datatypes\utils.js:40:34)
    at ProtoDef.read (D:\_Projects_Node\mcauth-server\node_modules\minecraft-protocol\node_modules\protodef\dist\protodef.js:135:31)
    at D:\_Projects_Node\mcauth-server\node_modules\minecraft-protocol\node_modules\protodef\dist\datatypes\structures.js:82:32
    at tryCatch (D:\_Projects_Node\mcauth-server\node_modules\minecraft-protocol\node_modules\protodef\dist\utils.js:80:12)
    at tryDoc (D:\_Projects_Node\mcauth-server\node_modules\minecraft-protocol\node_modules\protodef\dist\utils.js:87:10)
    at D:\_Projects_Node\mcauth-server\node_modules\minecraft-protocol\node_modules\protodef\dist\datatypes\structures.js:81:5
    at Array.forEach (native)
    at ProtoDef.readContainer (D:\_Projects_Node\mcauth-server\node_modules\minecraft-protocol\node_modules\protodef\dist\datatypes\structures.js:76:12)
    at ProtoDef.read (D:\_Projects_Node\mcauth-server\node_modules\minecraft-protocol\node_modules\protodef\dist\protodef.js:47:25)
    at ProtoDef.read (D:\_Projects_Node\mcauth-server\node_modules\minecraft-protocol\node_modules\protodef\dist\protodef.js:135:31)
```   

However, trying to connect with the wrong version outputs a "Wrong protocol version" message to the client, without the server crashing. 
![](https://i.inventivetalent.org/2017/02/27/0cb03413be_javaw.png)

**Comment by InventivetalentDev** [comment]
When I add the `beforePing` option with a callback, the function gets called but the crash still occurs even if the callback is not called.

**Comment by roblabla** [comment]
The server crashes ? I thought we fixed that...

**Comment by rom1504** [comment]
Gotta merge

**Comment by roblabla** [comment]
In the meantime, in the server, you can do

```
server.on('connection', function(client) {
    client.on('error', function(err) {
        client.end();
    });
});
```

**Comment by roblabla** [comment]
#463

**Comment by InventivetalentDev** [comment]
@roblabla Cool, thank you! :smiley:
