### ISSUE TITLE
Crashes on client connect

### ISSUE THREAD

**Issue by theLMGN** [PrismarineJS/node-minecraft-protocol#527]
```header.js:9
    at Object.module.exports.player (c:\Users\theLMGN\Desktop\stuff\node_modules\flying-squid\dist\lib\plugins\header.js:17:59)
    at c:\Users\theLMGN\Desktop\stuff\node_modules\flying-squid\dist\lib\plugins\login.js:67:54
    at Array.forEach (<anonymous>)
    at Object._callee$ (c:\Users\theLMGN\Desktop\stuff\node_modules\flying-squid\dist\lib\plugins\login.js:66:28)
    at tryCatch (c:\Users\theLMGN\Desktop\stuff\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (c:\Users\theLMGN\Desktop\stuff\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (c:\Users\theLMGN\Desktop\stuff\node_modules\regenerator-runtime\runtime.js:114:21)
    at tryCatch (c:\Users\theLMGN\Desktop\stuff\node_modules\regenerator-runtime\runtime.js:62:40)
    at maybeInvokeDelegate (c:\Users\theLMGN\Desktop\stuff\node_modules\regenerator-runtime\runtime.js:358:18)
    at Generator.invoke [as _invoke] (c:\Users\theLMGN\Desktop\stuff\node_modules\regenerator-runtime\runtime.js:270:32)
    at Generator.prototype.(anonymous function) [as next] (c:\Users\theLMGN\Desktop\stuff\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (c:\Users\theLMGN\Desktop\stuff\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at c:\Users\theLMGN\Desktop\stuff\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (c:\Users\theLMGN\Desktop\stuff\node_modules\core-js\library\modules\_export.js:35:28)
    at Server.<anonymous> (c:\Users\theLMGN\Desktop\stuff\node_modules\babel-runtime\helpers\asyncToGenerator.js:14:12)```

**Comment by theLMGN** [comment]
Wrong repo i think.
