### ISSUE TITLE
Deserialization error

### ISSUE THREAD

**Issue by Wqrld** [PrismarineJS/node-minecraft-protocol#530]
```var mineflayer = require('mineflayer');
var bot = mineflayer.createBot({
  host: "ip", // optional
  port: 25565,       // optional
  username: "right", // email and password are required only for
  password: "right",          // online-mode=true servers
});
bot.on('chat', function(username, message) {
});
```

gives:
```
pi@raspberry:~/factions $ node index.js
/home/pi/node_modules/minecraft-protocol/src/transforms/framing.js:76
          throw e;
          ^

Error: Deserialization error for play.toClient : write callback called multiple times
    at afterTransform (/home/pi/node_modules/protodef/node_modules/readable-stream/lib/_stream_transform.js:96:33)
    at TransformState.afterTransform (/home/pi/node_modules/protodef/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at FullPacketParser._transform (/home/pi/node_modules/protodef/src/serializer.js:85:7)
    at FullPacketParser.Transform._read (/home/pi/node_modules/protodef/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at FullPacketParser.Transform._write (/home/pi/node_modules/protodef/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/home/pi/node_modules/protodef/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/home/pi/node_modules/protodef/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at FullPacketParser.Writable.write (/home/pi/node_modules/protodef/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at Decompressor.ondata (/home/pi/node_modules/minecraft-protocol/node_modules/readable-stream/lib/_stream_readable.js:612:20)
    at Decompressor.emit (events.js:159:13)
```
when starting

  edit: seems like the update went wrong or something 1sec

**Comment by Wqrld** [comment]
moving to the mineflayer github
