### ISSUE TITLE
Incompatible servers

### ISSUE THREAD

**Issue by DesWurstes** [PrismarineJS/node-minecraft-protocol#532]
Code:

```
'use strict';

const mc = require('minecraft-protocol');

if(process.argv.length < 4 || process.argv.length > 6) {
  console.log("Usage : node echo.js <host> <port> [<name>] [<password>]");
  process.exit(1);
}

const client = mc.createClient({
  version: false,
  host: process.argv[2],
  port: parseInt(process.argv[3]),
  username: process.argv[4] ? process.argv[4] : "echo",
  password: process.argv[5]
});

client.on('connect', function() {
  console.info('connected');
});
client.on('disconnect', function(packet) {
  console.log('disconnected: '+ packet.reason);
});
client.on('end', function() {
  console.log('disconnected: ');
});
client.on('close', function() {
  console.log('disconnected: ');
});
client.on('timeout', function() {
  console.log('disconnected: ');
});
```

Found incompatible servers:

- Hypixel:
```
connected
events.js:136
      throw er; // Unhandled 'error' event
      ^

PartialReadError: Deserialization error for play.toClient.update_time.time : Read error for params.update_time.time : undefined
    at new ExtendableError (/Users/nj/Downloads/node-minecraft-protocol-master/node_modules/protodef/src/utils.js:75:11)
    at new PartialReadError (/Users/nj/Downloads/node-minecraft-protocol-master/node_modules/protodef/src/utils.js:81:5)
    at ProtoDef.readI64 (/Users/nj/Downloads/node-minecraft-protocol-master/node_modules/protodef/src/datatypes/numeric.js:5:11)
    at ProtoDef.read (/Users/nj/Downloads/node-minecraft-protocol-master/node_modules/protodef/src/protodef.js:127:29)
    at tryDoc (/Users/nj/Downloads/node-minecraft-protocol-master/node_modules/protodef/src/datatypes/structures.js:46:32)
    at tryCatch (/Users/nj/Downloads/node-minecraft-protocol-master/node_modules/protodef/src/utils.js:63:16)
    at tryDoc (/Users/nj/Downloads/node-minecraft-protocol-master/node_modules/protodef/src/utils.js:67:10)
    at typeArgs.forEach (/Users/nj/Downloads/node-minecraft-protocol-master/node_modules/protodef/src/datatypes/structures.js:45:5)
    at Array.forEach (<anonymous>)
    at ProtoDef.readContainer (/Users/nj/Downloads/node-minecraft-protocol-master/node_modules/protodef/src/datatypes/structures.js:44:12)
```

- Mineplex (Bungeecord):

Quits ASAP it prints connected.

- 2b2t (?):

```
connected
/Users/nj/Downloads/node-minecraft-protocol-master/src/transforms/framing.js:76
          throw e;
          ^

Error: Deserialization error for play.toClient : write callback called multiple times
    at afterTransform (/Users/nj/Downloads/node-minecraft-protocol-master/node_modules/readable-stream/lib/_stream_transform.js:96:33)
    at TransformState.afterTransform (/Users/nj/Downloads/node-minecraft-protocol-master/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at FullPacketParser._transform (/Users/nj/Downloads/node-minecraft-protocol-master/node_modules/protodef/src/serializer.js:85:7)
    at FullPacketParser.Transform._read (/Users/nj/Downloads/node-minecraft-protocol-master/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at FullPacketParser.Transform._write (/Users/nj/Downloads/node-minecraft-protocol-master/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/Users/nj/Downloads/node-minecraft-protocol-master/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/Users/nj/Downloads/node-minecraft-protocol-master/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at FullPacketParser.Writable.write (/Users/nj/Downloads/node-minecraft-protocol-master/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at Decompressor.ondata (/Users/nj/Downloads/node-minecraft-protocol-master/node_modules/readable-stream/lib/_stream_readable.js:612:20)
    at Decompressor.emit (events.js:159:13)
```

**Comment by rom1504** [comment]
Thank you for doing the list ;)

**Comment by rom1504** [comment]
@DesWurstes about the error for 2b2t ("write callback called multiple times") can you run npm update and try again ? I believe I fixed something in protodef that was hidding the actual error.
@wqrld can you also try ? (related https://github.com/PrismarineJS/mineflayer/issues/624)

**Comment by DesWurstes** [comment]
Yes, that error was solved. Now another one:

```
connected
disconnected: {"extra":[{"color":"gold","text":"You have lost connection to the server"}],"text":""}
disconnected: 
```

Weird?

**Comment by rom1504** [comment]
looks like you were kicked. I'd say the next step here is connecting through the nmp proxy and checking if that server expect extra actions from you (compared to vanilla) https://github.com/PrismarineJS/node-minecraft-protocol/tree/master/examples/proxy

**Comment by lixfel** [comment]
Tested with a direct connect to a spigot server without problems.
seagiants.eu (Im there a plugin-developer) with bungee throws following error:

On clientside:
/Mineflayer/node_modules/minecraft-protocol/src/transforms/framing.js:76
          throw e;
          ^

Error: Deserialization error for play.toClient : Chunk size is 10 but only 2 was read [object ArrayBuffer]
    at FullPacketParser._transform (/Mineflayer/node_modules/protodef/src/serializer.js:78:15)
    at FullPacketParser.Transform._read (/Mineflayer/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at FullPacketParser.Transform._write (/Mineflayer/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/Mineflayer/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/Mineflayer/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at FullPacketParser.Writable.write (/Mineflayer/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at Decompressor.ondata (/Mineflayer/node_modules/readable-stream/lib/_stream_readable.js:612:20)
    at emitOne (events.js:96:13)
    at Decompressor.emit (events.js:188:7)
    at addChunk (/Mineflayer/node_modules/readable-stream/lib/_stream_readable.js:284:12)

In the Bungeecord-Server-Logs nothing suspicious.
On Serverside:
[19:35:37] [User Authenticator #47/INFO]: UUID of player [Name] is 8abd72d9-5f4b-49a1-9e67-61c3df8aa362
[19:35:37] [Server thread/INFO]: [Name][/[IP]:47960] logged in with entity id 69 at ([Lobby2]993.1155324622869, 111.0625, 0.07242189681469641)
[19:35:37] [Server thread/INFO]: [Name] lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: 77

**Comment by lixfel** [comment]
Exactly same error after npm update ;)
`/Mineflayer/node_modules/minecraft-protocol/src/transforms/framing.js:76
          throw e;
          ^

Error: Deserialization error for play.toClient : Chunk size is 10 but only 2 was read [object ArrayBuffer]
    at FullPacketParser._transform (/Mineflayer/node_modules/protodef/src/serializer.js:78:15)
    at FullPacketParser.Transform._read (/Mineflayer/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at FullPacketParser.Transform._write (/Mineflayer/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/Mineflayer/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/Mineflayer/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at FullPacketParser.Writable.write (/Mineflayer/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at Decompressor.ondata (/Mineflayer/node_modules/readable-stream/lib/_stream_readable.js:612:20)
    at emitOne (events.js:96:13)
    at Decompressor.emit (events.js:188:7)
    at addChunk (/Mineflayer/node_modules/readable-stream/lib/_stream_readable.js:284:12)`

**Comment by rom1504** [comment]
Weird, can you try to delete your node_modules and npm install and try
again ?

**Comment by DesWurstes** [comment]
Hypixel:
```
connected
/Users/nj/Downloads/node-minecraft-protocol-master 2/src/transforms/framing.js:76
          throw e;
          ^

Error [ERR_UNHANDLED_ERROR]: Deserialization error for status.toClient : Unhandled error. (null)
    at Client.emit (events.js:141:19)
    at /Users/nj/Downloads/node-minecraft-protocol-master 2/src/client/autoVersion.js:14:12
    at Client.<anonymous> (/Users/nj/Downloads/node-minecraft-protocol-master 2/src/ping.js:29:7)
    at Object.onceWrapper (events.js:255:19)
    at Client.emit (events.js:160:13)
    at FullPacketParser.deserializer.on (/Users/nj/Downloads/node-minecraft-protocol-master 2/src/client.js:103:12)
    at FullPacketParser.emit (events.js:160:13)
    at addChunk (/Users/nj/Downloads/node-minecraft-protocol-master 2/node_modules/readable-stream/lib/_stream_readable.js:284:12)
    at readableAddChunk (/Users/nj/Downloads/node-minecraft-protocol-master 2/node_modules/readable-stream/lib/_stream_readable.js:271:11)
    at FullPacketParser.Readable.push (/Users/nj/Downloads/node-minecraft-protocol-master 2/node_modules/readable-stream/lib/_stream_readable.js:238:10)
```
2b2t:
```
/Users/nj/Downloads/node-minecraft-protocol-master 2/src/transforms/framing.js:76
          throw e;
          ^

Error [ERR_UNHANDLED_ERROR]: Deserialization error for status.toClient : Unhandled error. (null)
    at Client.emit (events.js:141:19)
    at /Users/nj/Downloads/node-minecraft-protocol-master 2/src/client/autoVersion.js:14:12
    at Client.<anonymous> (/Users/nj/Downloads/node-minecraft-protocol-master 2/src/ping.js:29:7)
    at Object.onceWrapper (events.js:255:19)
    at Client.emit (events.js:160:13)
    at FullPacketParser.deserializer.on (/Users/nj/Downloads/node-minecraft-protocol-master 2/src/client.js:103:12)
    at FullPacketParser.emit (events.js:160:13)
    at addChunk (/Users/nj/Downloads/node-minecraft-protocol-master 2/node_modules/readable-stream/lib/_stream_readable.js:284:12)
    at readableAddChunk (/Users/nj/Downloads/node-minecraft-protocol-master 2/node_modules/readable-stream/lib/_stream_readable.js:271:11)
    at FullPacketParser.Readable.push (/Users/nj/Downloads/node-minecraft-protocol-master 2/node_modules/readable-stream/lib/_stream_readable.js:238:10)
```
Mineplex:
```
/Users/nj/Downloads/node-minecraft-protocol-master 2/src/transforms/framing.js:76
          throw e;
          ^

Error [ERR_UNHANDLED_ERROR]: Deserialization error for status.toClient : Unhandled error. (null)
    at Client.emit (events.js:141:19)
    at /Users/nj/Downloads/node-minecraft-protocol-master 2/src/client/autoVersion.js:14:12
    at Client.<anonymous> (/Users/nj/Downloads/node-minecraft-protocol-master 2/src/ping.js:29:7)
    at Object.onceWrapper (events.js:255:19)
    at Client.emit (events.js:160:13)
    at FullPacketParser.deserializer.on (/Users/nj/Downloads/node-minecraft-protocol-master 2/src/client.js:103:12)
    at FullPacketParser.emit (events.js:160:13)
    at addChunk (/Users/nj/Downloads/node-minecraft-protocol-master 2/node_modules/readable-stream/lib/_stream_readable.js:284:12)
    at readableAddChunk (/Users/nj/Downloads/node-minecraft-protocol-master 2/node_modules/readable-stream/lib/_stream_readable.js:271:11)
    at FullPacketParser.Readable.push (/Users/nj/Downloads/node-minecraft-protocol-master 2/node_modules/readable-stream/lib/_stream_readable.js:238:10)
```

**Comment by rom1504** [comment]
You need to do client.on('error', err => console.log(err))

**Comment by rom1504** [comment]
ah there was still a small error in protodef error, can you do it again ? (rm node_modules then npm install and retry)

**Comment by DesWurstes** [comment]
Now the servers print lots of "wrong chunk size"-y things. Would pasting the big log here help?

**Comment by rom1504** [comment]
yes, you can put it in a gist.github.com if it's too long

**Comment by rom1504** [comment]
anyway, I checked what you posted already

> Error: Deserialization error for play.toClient : Chunk size is 14 but only 2 was read ; partial packet : undefinedpacket. ; buffer : 4803000000000000000000000000

48 means 0x48 so title packet

https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.12.2/protocol.json#L2789

http://wiki.vg/Protocol#Title 

it would seem we are indeed missing some cases in the protocol file here (in particular action = 3 here)

I'll fix it.

If you can repost your logs with the updated protodef that gives the useful error, we might be able to find more problems.

**Comment by rom1504** [comment]
@DesWurstes there was also a bug in autoversion, recently introduced, I fixed it, also pull nmp (I'll do a new release soon)

**Comment by DesWurstes** [comment]
https://gist.github.com/DesWurstes/29d908b1cfa5f2cac2046cbf68d19643

**Comment by lixfel** [comment]
My Errorlist with logerror on after reinstalling:
https://gist.github.com/lixfel/021c7d45960ddff17164295192b16114

**Comment by rom1504** [comment]
I finally fixed the [object object] in the error, can you both try again ?

I'm going to try too and start fixing stuff

**Comment by rom1504** [comment]
ok I fixed the packet_title error and released a new version.
Can you update npm and update your logs ?

I'll continue checking your logs for other bugs.

**Comment by rom1504** [comment]
can you also tell me what version you are using with each log ?

**Comment by lixfel** [comment]
Ok, fixed my bug with a specified version (1.12.1). Seems that Bungee, which supports many versions at once, that mineflayer takes the wrong version, which supports bungee, but not the server behind the bungee.

**Comment by rom1504** [comment]
can you please put the servers host and port  you are testing on in the issue ? I can probably look them up online but it would make it faster totest

**Comment by MeWoody** [comment]
Updated to last version of Mineflayer, gives a similar error but without any "x but expected Y"?

```
Error: Deserialization error for play.toClient : Chunk size is
    at FullPacketParser._transform (C:\Users\MYNAME\Desktop\AltCheckBot\node_modules\protodef\src\serializer.js:78:15)
    at FullPacketParser.Transform._read (C:\Users\MYNAME\Desktop\AltCheckBot\node_modules\readable-stream\lib\_stream_transform.js:182:10)
    at FullPacketParser.Transform._write (C:\Users\MYNAME\Desktop\AltCheckBot\node_modules\readable-stream\lib\_stream_transform.js:170:83)
    at doWrite (C:\Users\MYNAME\Desktop\AltCheckBot\node_modules\readable-stream\lib\_stream_writable.js:406:64)
    at writeOrBuffer (C:\Users\MYNAME\Desktop\AltCheckBot\node_modules\readable-stream\lib\_stream_writable.js:395:5)
    at FullPacketParser.Writable.write (C:\Users\MYNAME\Desktop\AltCheckBot\node_modules\readable-stream\lib\_stream_writable.js:322:11)
    at Decompressor.ondata (C:\Users\MYNAME\Desktop\AltCheckBot\node_modules\readable-stream\lib\_stream_readable.js:612:20)
    at emitOne (events.js:116:13)
    at Decompressor.emit (events.js:211:7)
    at addChunk (C:\Users\MYNAME\Desktop\AltCheckBot\node_modules\readable-stream\lib\_stream_readable.js:284:12)

**Comment by SuperOP535** [comment]
Works fine on Bungee -> Vanilla -> Vanilla. Transfer works ok

**Comment by 1zerozero2** [comment]
2b2t uses Waterfall which is a fork of BungeeCord.

**Comment by unnown** [comment]
play.riftmc.org

**Comment by rom1504** [comment]
I think we should setup automatic tests on all these servers, so we have more data.

**Comment by Wqrld** [comment]
im getting a lot of end of files too on saicopvp.com
```
{ Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:133:17) errno: -5, code: 'Z_BUF_ERROR' }
problem inflating chunk
uncompressed length 1091
compressed length 889
hex c308789c04c039b2b3360000e0f76726337f930b2447783379ac36af78858d5984418059a58ecd0621f0826c40c7499d32b9459a5429d2e620f97e7dfbc6ff797efff92ff0e76fc52f7fff31f37f7ff21a5650ef3af6cdba55bf7d67cdc29e8f66faef87667584221369259fda32df753e31448f20c58fc10c0992e02199c0b85f4b09df4a2b75b00e3680d42d3e54328c778a979904f15045246d3d82162f737a2f0302e4958cb25307bab9ab6ce785073ae1446dcb2ce9fcce81383fb5a521beca81d126ae44d0cd5d6da54a6da72bcebdce1fa72e1198137760d3ac8e580d73e777ceb5b64fb3df69afda4a95da4e579c7bcf32a34f9cc1156558700795d6faa780f356a87387babca61e010ae29ee0c5264143a820295920871d8c8188494dd160f6982009c580436e2830a62d944e03e4bd80081d3c0bb79020d9cf3cd9237b8278d2b9bac3707e6ab1650a28029b667558299d68a9830d18e154644277cec5cf73f8f5f5edf71fcb23b6db7e3b5df0b1affd6951686e5ee790c8e7ba80cc5a3ea3227ca54bd54b35c745c22c485a5efbe79153dfd1f4ae4093a7b89e91800dfb505876e3f5ce4c13631de5e356d4e4b5b16f74cf35e643c7a41d15ed7cb7b42c0af507d8dd8387a07a280c8064dcf2d45e2268b587d6ec1f5dabacb7790772cb9cdacff367ba4d3511d66cbdeb5a7f4b96641c701aa83d0de346bb12beb8a2ee06e032f7d28add13331437ec8a4059efa1fe78b9eb59de8aed513c1d83cd6449e749646a1847339f3fb5ab1558fe5d17693757a5e55e8fa6fdaec4d2c167fe7619b42e707d5063c9951faae9111989605af577ff25c24b796003b0ab503682b5115ac3d5da91c7213afac20075ae6d4f46f9110dbc177d2b31f639579fb52ed84f4c0ec89c5792348b75718d0f6c5dd21135381861740c2aba66f9c6de88b558e9db6c00f16d07a9f77cde44a1f4c803f0f69039e9bc7d58d9c5e5513296975c712c76a98b75579d3ea65998a05a262660541de2dd3b5f6d3fe5693e5a66888fbbc7fb801ec15d08c273f1da96a68f5c845b778f2fcda366a6336f623715a2709feee2c64ebcc229f3bc34a8c527f5b533e0658eeea5f10a75a3adfd8f4076f548eb559b456737decbc2ecc0407eca674ef54d8cc2d39429a50cf01613b497179f814e15ccd9785a8344ca8ffb462b94b9a5eb5494b2192efb637e88a49e6a6c7bf6948decbfaf997b946d567dbdbdbdfd0f0000ffff
{ Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:133:17) errno: -5, code: 'Z_BUF_ERROR' }
problem inflating chunk
uncompressed length 890
compressed length 736
hex fa06789c04c03992b3c60200e099aaf7aa1cf82672fd6c0d8302076c824602d4883d830641b38dc4aa56ec633874e8cc37f0297c1647fe7e7c7cfef3f78f05ff02fff70733fff5dbf1dfc7cf663e5453bece0b19bf3e7f5aaad7b24ed5fcfb67456d368fb91e0b7e53240af15a8373da147801dcdd36058eaecc705469c1678fc28cec4c831
```

**Comment by rom1504** [comment]
That error is expected to be printed but it doesn't mean that it doesn't
work.

**Comment by renhiyama** [comment]
@rom1504 any updates on this? I'll try my best on solving this problem, however, I need some specific help. How can I contact you?

**Comment by rom1504** [comment]
What is "this" ? I think we should probably close this issue, not enough information and not actionable

**Comment by renhiyama** [comment]
@rom1504 bots cannot join modded servers, in my experience I had been trying out modded fabric servers which added new blocks and entities (biomes o' plenty mod) - which threw the error about chunk size expectations were not met with the amount of chunk size received. This error was shown in protodef npm package.
Looking at this issue, it looks like other people tried joining modded servers which should be vanilla friendly but their bots still fail to join those servers, sometimes with the same issue as mine, other times different issue.
