### ISSUE TITLE
Echo client crashes 1.12.2

### ISSUE THREAD

**Issue by duralakun** [PrismarineJS/node-minecraft-protocol#552]
I just downloaded the server file from mojang and tried to start the echo example:

```
var mc = require('minecraft-protocol');
var client = mc.createClient({
  host: "localhost",   // optional
  port: 25565,         // optional
  username: "email@example.com",
  password: "12345678",
});
client.on('chat', function(packet) {
  // Listen for chat messages and echo them back.
  var jsonMsg = JSON.parse(packet.message);
  if(jsonMsg.translate == 'chat.type.announcement' || jsonMsg.translate == 'chat.type.text') {
    var username = jsonMsg.with[0].text;
    var msg = jsonMsg.with[1];
    if(username === client.username) return;
    client.write('chat', {message: msg});
  }
});
```
it can login but, it crashes as soon as i type "say hi" in the server console

```
/node_modules/minecraft-protocol/src/transforms/framing.js:76
          throw e;
          ^

TypeError: Deserialization error for play.toClient.toServer.chat.message : Serialization error for play.toServer.chat.message : SizeOf error for params.chat.message : "string" must be a string, Buffer, or ArrayBuffer
    at Function.byteLength (buffer.js:481:11)
    at ProtoDef.sizeOfPString (/node_modules/protodef/src/datatypes/utils.js:127:25)
    at ProtoDef.sizeOf (/node_modules/protodef/src/protodef.js:44:27)
    at ProtoDef.sizeOf (/node_modules/protodef/src/protodef.js:145:31)
    at tryDoc (/node_modules/protodef/src/datatypes/structures.js:72:30)
    at tryCatch (/node_modules/protodef/src/utils.js:63:16)
    at tryDoc (/node_modules/protodef/src/utils.js:67:10)
    at typeArgs.reduce (/node_modules/protodef/src/datatypes/structures.js:72:12)
    at Array.reduce (<anonymous>)
    at ProtoDef.sizeOfContainer (/node_modules/protodef/src/datatypes/structures.js:71:25)

```

is it not compatible with 1.12.2? Or did i maybe mess something up?

**Comment by rom1504** [comment]
looks like the echo example is broken.
Replace msg with for example "test" and it'll work.

**Comment by duralakun** [comment]
ty for this super fast answer, i will try it

**Comment by rom1504** [comment]
just do that https://github.com/PrismarineJS/mineflayer/issues/660

basically test that things work, add 1.12.2 in the tested version and make
a PR

**Comment by duralakun** [comment]
I tested again the echo example here and found out it works if a normal player writes "hi", but crashes if the server writes "hi"
When the server writes "hi" and i stringify the msg it says: <player> {"extra":[{"text":"hi"}],"text":""}
I will leave it at that and will now do tests on mineflayer

**Comment by rom1504** [comment]
ah yes it's just a basic example, it will not work with all cases (unlike mineflayer)
