### ISSUE TITLE
Consider supporting non vanilla servers

### ISSUE THREAD

**Issue by kotik1998** [PrismarineJS/node-minecraft-protocol#554]
Chunk size is 44 but only 25 was read ; partial packet : [object Object]; buffer :440a76696176657273696f6e000a76696176657273696f6e00000000056e657665720001074161726f6e414b
Error occured
{ PartialReadError: Deserialization error for play.toClient.update_time.time : Read error for params.update_time.time : undefined
    at PartialReadError.ExtendableError (C:\Users\Kotik\node_modules\protodef\src\utils.js:75:11)
    at PartialReadError (C:\Users\Kotik\node_modules\protodef\src\utils.js:81:5)
    at ProtoDef.readI64 (C:\Users\Kotik\node_modules\protodef\src\datatypes\numeric.js:5:11)
    at ProtoDef.read (C:\Users\Kotik\node_modules\protodef\src\protodef.js:127:29)
    at tryDoc (C:\Users\Kotik\node_modules\protodef\src\datatypes\structures.js:46:32)
    at tryCatch (C:\Users\Kotik\node_modules\protodef\src\utils.js:63:16)
    at tryDoc (C:\Users\Kotik\node_modules\protodef\src\utils.js:67:10)
    at typeArgs.forEach (C:\Users\Kotik\node_modules\protodef\src\datatypes\structures.js:45:5)
    at Array.forEach (native)
    at ProtoDef.readContainer (C:\Users\Kotik\node_modules\protodef\src\datatypes\structures.js:44:12)
  name: 'PartialReadError',
  message: 'Deserialization error for play.toClient.update_time.time : Read error for params.update_time.time : undefined',
  partialReadError: true,
  field: 'play.toClient.update_time.time' }

**Comment by kotik1998** [comment]
i combined the chat + proxy from your examples

**Comment by kotik1998** [comment]
everything logged on, and then that came in.

**Comment by kotik1998** [comment]
C:\Users\Kotik\Desktop>node aa.js *********** 25565 ******* ******
connecting to *********.com:25565
user: ******************
Successfully connected to *********:25565
Chunk size is 44 but only 25 was read ; partial packet : [object Object]; buffer :440a76696176657273696f6e000a76696176657273696f6e00000000056e657665720001074161726f6e414b
Error occured
{ PartialReadError: Deserialization error for play.toClient.update_time.time : Read error for params.update_time.time : undefined
    at PartialReadError.ExtendableError (C:\Users\Kotik\node_modules\protodef\src\utils.js:75:11)
    at PartialReadError (C:\Users\Kotik\node_modules\protodef\src\utils.js:81:5)
    at ProtoDef.readI64 (C:\Users\Kotik\node_modules\protodef\src\datatypes\numeric.js:5:11)
    at ProtoDef.read (C:\Users\Kotik\node_modules\protodef\src\protodef.js:127:29)
    at tryDoc (C:\Users\Kotik\node_modules\protodef\src\datatypes\structures.js:46:32)
    at tryCatch (C:\Users\Kotik\node_modules\protodef\src\utils.js:63:16)
    at tryDoc (C:\Users\Kotik\node_modules\protodef\src\utils.js:67:10)
    at typeArgs.forEach (C:\Users\Kotik\node_modules\protodef\src\datatypes\structures.js:45:5)
    at Array.forEach (native)
    at ProtoDef.readContainer (C:\Users\Kotik\node_modules\protodef\src\datatypes\structures.js:44:12)
  name: 'PartialReadError',
  message: 'Deserialization error for play.toClient.update_time.time : Read error for params.update_time.time : undefined',
  partialReadError: true,
  field: 'play.toClient.update_time.time' }

this is only the chat example that i used from your examples.

**Comment by kotik1998** [comment]
its a server with 17. up to 1.12 compatible 

ip is fadecloud.com

**Comment by rom1504** [comment]
ah that means we have no idea which version has been used because nmp is also 1.7 to 1.12 compatible.

**Comment by kotik1998** [comment]
but is there any waay to log in, for example 1.8
the bot only log in using 1.8 protocol?

**Comment by kotik1998** [comment]
i was watching this post https://github.com/PrismarineJS/node-minecraft-protocol/issues/481 and he has a line where he join with the 1.8 protocol if im not sure.

**Comment by kotik1998** [comment]
okay, i found a fix, simply add a Version:"1.12" to the bot. and were good to go :)

**Comment by kotik1998** [comment]
ok, i ran in another problem, when im trying to login with another proxy ( and having another running) this appears, Error occured
{ Error: Deserialization error for login.toClient : Read error for name : 111 is not in the mappings value
    at ProtoDef.readMapper (C:\Users\Kotik\node_modules\protodef\src\datatypes\utils.js:27:31)
    at ProtoDef.read (C:\Users\Kotik\node_modules\protodef\src\protodef.js:127:29)
    at tryDoc (C:\Users\Kotik\node_modules\protodef\src\datatypes\structures.js:46:32)
    at tryCatch (C:\Users\Kotik\node_modules\protodef\src\utils.js:63:16)
    at tryDoc (C:\Users\Kotik\node_modules\protodef\src\utils.js:67:10)
    at typeArgs.forEach (C:\Users\Kotik\node_modules\protodef\src\datatypes\structures.js:45:5)
    at Array.forEach (native)
    at ProtoDef.readContainer (C:\Users\Kotik\node_modules\protodef\src\datatypes\structures.js:44:12)
    at ProtoDef.read (C:\Users\Kotik\node_modules\protodef\src\protodef.js:39:25)
    at ProtoDef.read (C:\Users\Kotik\node_modules\protodef\src\protodef.js:127:29) field: 'login.toClient' }
