### ISSUE TITLE
Example usage code from README.md is not working

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [PrismarineJS/node-minecraft-protocol#622]
When using [this](https://github.com/PrismarineJS/node-minecraft-protocol#echo-client-example) code, client crashes at the moment it receives message from server.

What I did is that I sent next command from server console: `>say test test test...` and client immediately crashed.

```
/home/korindou/Code/MCCC/node_modules/.registry.npmjs.org/minecraft-protocol/1.8.3/node_modules/minecraft-protocol/src/transforms/framing.js:66
          } else { throw e }
                   ^

TypeError [ERR_INVALID_ARG_TYPE]: Serialization error for play.toServer.chat.message : SizeOf error for params.chat.message : The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type object
    at Function.byteLength (buffer.js:515:11)
    at ProtoDef.sizeOfPString (/home/korindou/Code/MCCC/node_modules/.registry.npmjs.org/protodef/1.6.9/node_modules/protodef/src/datatypes/utils.js:127:25)
    at ProtoDef.sizeOf (/home/korindou/Code/MCCC/node_modules/.registry.npmjs.org/protodef/1.6.9/node_modules/protodef/src/protodef.js:40:67)
    at ProtoDef.sizeOf (/home/korindou/Code/MCCC/node_modules/.registry.npmjs.org/protodef/1.6.9/node_modules/protodef/src/protodef.js:127:31)
    at tryDoc (/home/korindou/Code/MCCC/node_modules/.registry.npmjs.org/protodef/1.6.9/node_modules/protodef/src/datatypes/structures.js:72:30)
    at tryCatch (/home/korindou/Code/MCCC/node_modules/.registry.npmjs.org/protodef/1.6.9/node_modules/protodef/src/utils.js:50:16)
    at tryDoc (/home/korindou/Code/MCCC/node_modules/.registry.npmjs.org/protodef/1.6.9/node_modules/protodef/src/utils.js:54:10)
    at typeArgs.reduce (/home/korindou/Code/MCCC/node_modules/.registry.npmjs.org/protodef/1.6.9/node_modules/protodef/src/datatypes/structures.js:72:12)
    at Array.reduce (<anonymous>)
    at ProtoDef.sizeOfContainer (/home/korindou/Code/MCCC/node_modules/.registry.npmjs.org/protodef/1.6.9/node_modules/protodef/src/datatypes/structures.js:71:25)
Emitted 'error' event at:
    at Serializer.serializer.on (/home/korindou/Code/MCCC/node_modules/.registry.npmjs.org/minecraft-protocol/1.8.3/node_modules/minecraft-protocol/src/client.js:58:12)
    at Serializer.emit (events.js:189:13)
    at onwriteError (/home/korindou/Code/MCCC/node_modules/.registry.npmjs.org/readable-stream/3.2.0/node_modules/readable-stream/lib/_stream_writable.js:420:12)
    at onwrite (/home/korindou/Code/MCCC/node_modules/.registry.npmjs.org/readable-stream/3.2.0/node_modules/readable-stream/lib/_stream_writable.js:446:11)
    at WritableState.onwrite (/home/korindou/Code/MCCC/node_modules/.registry.npmjs.org/readable-stream/3.2.0/node_modules/readable-stream/lib/_stream_writable.js:158:5)
    at Serializer.afterTransform (/home/korindou/Code/MCCC/node_modules/.registry.npmjs.org/readable-stream/3.2.0/node_modules/readable-stream/lib/_stream_transform.js:89:3)
    at Serializer._transform (/home/korindou/Code/MCCC/node_modules/.registry.npmjs.org/protodef/1.6.9/node_modules/protodef/src/serializer.js:20:14)
    at Serializer.Transform._read (/home/korindou/Code/MCCC/node_modules/.registry.npmjs.org/readable-stream/3.2.0/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at Serializer.Transform._write (/home/korindou/Code/MCCC/node_modules/.registry.npmjs.org/readable-stream/3.2.0/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/home/korindou/Code/MCCC/node_modules/.registry.npmjs.org/readable-stream/3.2.0/node_modules/readable-stream/lib/_stream_writable.js:405:139)
```

**Comment by rom1504** [comment]
Yeah it doesn't use the server console. That example assumes normal chat
