### ISSUE TITLE
Error on Login.

### ISSUE THREAD

**Issue by RowanHall** [PrismarineJS/node-minecraft-protocol#625]
When logging in to mc.travcraft.net:25565 I receive this error:

`PartialReadError: Deserialization error for play.toClient.teams.players : Read error for params.teams.players : Missing characters in string, found size is 97 expected size was 188
    at new ExtendableError (C:\Users\rowan\node_modules\protodef\src\utils.js:62:11)
    at new PartialReadError (C:\Users\rowan\node_modules\protodef\src\utils.js:68:5)
    at ProtoDef.readPString (C:\Users\rowan\node_modules\protodef\src\datatypes\utils.js:109:11)
    at ProtoDef.read (C:\Users\rowan\node_modules\protodef\src\protodef.js:36:25)
    at ProtoDef.read (C:\Users\rowan\node_modules\protodef\src\protodef.js:110:29)
    at tryDoc (C:\Users\rowan\node_modules\protodef\src\datatypes\structures.js:19:42)
    at tryCatch (C:\Users\rowan\node_modules\protodef\src\utils.js:50:16)
    at tryDoc (C:\Users\rowan\node_modules\protodef\src\utils.js:54:10)
    at ProtoDef.readArray (C:\Users\rowan\node_modules\protodef\src\datatypes\structures.js:19:24)
    at ProtoDef.read (C:\Users\rowan\node_modules\protodef\src\protodef.js:110:29)
Emitted 'error' event at:
    at FullPacketParser.deserializer.on (C:\Users\rowan\node_modules\minecraft-protocol\src\client.js:71:12)
    at FullPacketParser.emit (events.js:185:15)
    at onwriteError (C:\Users\rowan\node_modules\protodef\node_modules\readable-stream\lib\_stream_writable.js:444:12)
    at onwrite (C:\Users\rowan\node_modules\protodef\node_modules\readable-stream\lib\_stream_writable.js:473:11)
    at WritableState.onwrite (C:\Users\rowan\node_modules\protodef\node_modules\readable-stream\lib\_stream_writable.js:168:5)
    at FullPacketParser.afterTransform (C:\Users\rowan\node_modules\protodef\node_modules\readable-stream\lib\_stream_transform.js:94:3)
    at FullPacketParser._transform (C:\Users\rowan\node_modules\protodef\src\serializer.js:79:14)
    at FullPacketParser.Transform._read (C:\Users\rowan\node_modules\protodef\node_modules\readable-stream\lib\_stream_transform.js:185:10)
    at FullPacketParser.Transform._write (C:\Users\rowan\node_modules\protodef\node_modules\readable-stream\lib\_stream_transform.js:173:83)
    at doWrite (C:\Users\rowan\node_modules\protodef\node_modules\readable-stream\lib\_stream_writable.js:429:139)`

**Comment by rom1504** [comment]
This is a warning. I guess we should specify that.
Do you have any actual issue ?

**Comment by RowanHall** [comment]
Well after this error / warning, the program exits, and the bot never logges on. 

Looking at it again, it's being thrown from events.js:165, do i have to catch it with:

client.on('error', [Function])?
