### ISSUE TITLE
client_socks_proxy issues

### ISSUE THREAD

**Issue by Zipdox** [PrismarineJS/node-minecraft-protocol#626]
```server@ubuntu:~/Documents/nodejs/chat$ node proxy.js play.example.com 25565 proxy.example.com 4145 example@example.com examplepassword
/home/server/Documents/nodejs/faggot spammer/proxy.js:14
    socks.createConnection({
          ^

TypeError: socks.createConnection is not a function
    at Object.connect (/home/server/Documents/nodejs/chat/proxy.js:14:11)
    at ping (/home/server/node_modules/minecraft-protocol/src/ping.js:50:11)
    at module.exports (/home/server/node_modules/minecraft-protocol/src/client/autoVersion.js:12:3)
    at Object.createClient (/home/server/node_modules/minecraft-protocol/src/createClient.js:37:34)
    at Object.<anonymous> (/home/server/Documents/nodejs/chat/proxy.js:12:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)```

Also where are the semicolons?

**Comment by rom1504** [comment]
You need to run npm install in the example directory.
See https://standardjs.com for style

**Comment by Zipdox** [comment]
**No semicolons**
Excuse me what the f*** did I just read?
