### ISSUE TITLE
Unexpected token < in JSON at position 0 (yggdrasil)

### ISSUE THREAD

**Issue by creepinson** [PrismarineJS/node-minecraft-protocol#657]
I am using minecraft-protocol version 1.9.4 and minecraft 1.14.4 and my createClient code crashed with the following error:

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /root/test/mc/node_modules/yggdrasil/lib/utils.js:28:23
    at IncomingMessage.<anonymous> (/root/test/mc/node_modules/phin/lib/phin.compiled.js:1:2162)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

all i have is a simple 
mc.createClient
and
client.on('disconnect'). and connect

**Comment by rom1504** [comment]
can you provide : 
* full code
* full error
* server
* os
* node version
* are you banned ? (ip or account)

**Comment by creepinson** [comment]
no i am not banned
code:
`var mc = require('minecraft-protocol');
var client = mc.createClient({
    version: "1.14.4",
    host: "Jean_Scoob.aternos.me",   // optional
    port: 25565,         // optional
    username: "myusername",
    password: "myactualpasswordcensored",
});
/*client.on('chat', function(packet) {
  // Listen for chat messages and echo them back.
  var jsonMsg = JSON.parse(packet.message);
  if(jsonMsg.translate == 'chat.type.announcement' || jsonMsg.translate == 'chat.type.text') {
    var username = jsonMsg.with[0].text;
    var msg = jsonMsg.with[1];
    if(username === client.username) return;
    client.write('chat', {message: msg});
  }
});*/
client.on('connect', function () {
    console.info('Successfully connected to ' + host + ':' + port);
    //client.write('chat', "i am a bot test made by creepinson101 im just testing");
})

client.on('disconnect', function (packet) {
    console.log('disconnected: ' + packet.reason)
});`
i am using node.js v8.10.0 and windows 10

**Comment by rom1504** [comment]
you can see there https://gitpod.io#snapshot/0d015ac0-d10c-4cd8-a1cc-7d4e99b23275
that this code works

**Comment by creepinson** [comment]
that's weird
it says invalid credentials (obviously)
but it didn't do that in my local workspace 
i will remove node_modules and update nodejs to see what is wrong

**Comment by creepinson** [comment]
it says chat is not in the mappings
how do i get the bot client to chat

**Comment by creepinson** [comment]
Error: Serialization error for login.toServer : SizeOf error for name : chat is not in the mappings value

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/node-minecraft-protocol/blob/b1ba01ed3cb4dbc7d2927969374fb322bb90a510/examples/client_echo/client_echo.js#L31

**Comment by creepinson** [comment]
it doesn't work
i did it in the client.on('connect')
is that a problem?
rror: Serialization error for login.toServer : SizeOf error for name : chat is not in the mappings value
    at ProtoDef.sizeOfMapper (/workspace/node-minecraft-protocol/node_modules/protodef/src/datatypes/utils.js:59:34)
    at ProtoDef.sizeOf (/workspace/node-minecraft-protocol/node_modules/protodef/src/protodef.js:127:31)
    at tryDoc (/workspace/node-minecraft-protocol/node_modules/protodef/src/datatypes/structures.js:72:30)
    at tryCatch (/workspace/node-minecraft-protocol/node_modules/protodef/src/utils.js:50:16)
    at tryDoc (/workspace/node-minecraft-protocol/node_modules/protodef/src/utils.js:54:10)
    at typeArgs.reduce (/workspace/node-minecraft-protocol/node_modules/protodef/src/datatypes/structures.js:72:12)
    at Array.reduce (<anonymous>)

**Comment by rom1504** [comment]
what's your current full code ?

**Comment by creepinson** [comment]
client.on('state', function (newState) {
  if (newState === states.PLAY) {
    client.write('chat', { message: "i am a bot test made by creepinson101 im just testing" })
  }
})
worked instead of
client.on('connect', function ()...

**Comment by rom1504** [comment]
yes
