### ISSUE TITLE
Error when sending a message using example code

### ISSUE THREAD

**Issue by Darvinschl** [PrismarineJS/node-minecraft-protocol#671]
If you are reporting a bug please report on these points :

* what you want to do (the objective in english)
use example "client_auto", it fails when i type "say hi" in console. For example "tell MyUserName hi" works
* what happened
Error, Client Disconnects
* what you expected to happen
Receive Message and send it back

In particular it will be useful to provide these informations :

* what happens when using a node-minecraft-protocol example?
I used one
* what minecraft-protocol version?
Release 1.10.0
* what server version?
1.15
* which server? (spigot, paper, vanilla, any particular plugins ?)
spigot
* what's the output of DEBUG="minecraft-protocol" node your_script.js ?
* what's the error msg?
```
C:\Users\darvi\OneDrive\Darvin\mcraft\node_modules\minecraft-protocol\src\transforms\framing.js:67
          } else { throw e }
                   ^

TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type object
    at Function.byteLength (buffer.js:693:11)
    at ProtoDef.sizeOfPString (C:\Users\darvi\OneDrive\Darvin\mcraft\node_modules\protodef\src\datatypes\utils.js:127:25)
    at ProtoDef.sizeOf (C:\Users\darvi\OneDrive\Darvin\mcraft\node_modules\protodef\src\protodef.js:40:67)
    at ProtoDef.sizeOf (C:\Users\darvi\OneDrive\Darvin\mcraft\node_modules\protodef\src\protodef.js:127:31)
    at C:\Users\darvi\OneDrive\Darvin\mcraft\node_modules\protodef\src\datatypes\structures.js:72:30
    at tryCatch (C:\Users\darvi\OneDrive\Darvin\mcraft\node_modules\protodef\src\utils.js:50:16)
    at tryDoc (C:\Users\darvi\OneDrive\Darvin\mcraft\node_modules\protodef\src\utils.js:54:10)
    at C:\Users\darvi\OneDrive\Darvin\mcraft\node_modules\protodef\src\datatypes\structures.js:72:12
    at Array.reduce (<anonymous>)
    at ProtoDef.sizeOfContainer (C:\Users\darvi\OneDrive\Darvin\mcraft\node_modules\protodef\src\datatypes\structures.js:71:25)
Emitted 'error' event on Client instance at:
    at Serializer.<anonymous> (C:\Users\darvi\OneDrive\Darvin\mcraft\node_modules\minecraft-protocol\src\client.js:63:12)
    at Serializer.emit (events.js:210:5)
    at onwriteError (C:\Users\darvi\OneDrive\Darvin\mcraft\node_modules\readable-stream\lib\_stream_writable.js:420:12)
    at onwrite (C:\Users\darvi\OneDrive\Darvin\mcraft\node_modules\readable-stream\lib\_stream_writable.js:446:11)
    at WritableState.onwrite (C:\Users\darvi\OneDrive\Darvin\mcraft\node_modules\readable-stream\lib\_stream_writable.js:158:5)
    at Serializer.afterTransform (C:\Users\darvi\OneDrive\Darvin\mcraft\node_modules\readable-stream\lib\_stream_transform.js:89:3)
    at Serializer._transform (C:\Users\darvi\OneDrive\Darvin\mcraft\node_modules\protodef\src\serializer.js:20:14)
    at Serializer.Transform._read (C:\Users\darvi\OneDrive\Darvin\mcraft\node_modules\readable-stream\lib\_stream_transform.js:177:10)
    at Serializer.Transform._write (C:\Users\darvi\OneDrive\Darvin\mcraft\node_modules\readable-stream\lib\_stream_transform.js:164:83)
    at doWrite (C:\Users\darvi\OneDrive\Darvin\mcraft\node_modules\readable-stream\lib\_stream_writable.js:405:139) {
  code: 'ERR_INVALID_ARG_TYPE',
  field: 'play.toServer.chat.message'
}
```
* what script is used (full code)?
https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/examples/client_auto/client_auto.js

INFO:
When using this example I have no errors!
https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/examples/client_chat/client_chat.js

**Comment by rom1504** [comment]
Did you change anything in the code of the example ?

**Comment by Darvinschl** [comment]
No I just copied. Is it maybe a bug causing the 1.15 minecraft server?

**Comment by rom1504** [comment]
I guess the chat format changed and client_auto.js is not parsing it
properly. I'll have a look

**Comment by lastuniverse** [comment]
if you use the example https://github.com/PrismarineJS/node-minecraft-protocol/tree/master/examples/proxy, adding this to it:
`	client.on('chat', function (packet) {
	  console.info("client packet.message:",packet);
	  client.write('chat', {message: 'qwerty'});
	});	
`
Then, when sending a message from the client to the chat, we see our message. Then, without receiving the "qwerty" message, the client crashes with an error:
`Internal Exeption: io.netty.handler.codec.DecoderExeption: com.google.gson.JsonSyntaxExeption: com.google.gson.stream.MalformedExeption: Use JsonReader.setLienient(true) to accept malformed JSON at line 1 column 1 path $`

**Comment by rom1504** [comment]
fixed
