### ISSUE TITLE
Unknown mapping value 27 on toClient.Login

### ISSUE THREAD

**Issue by matthewfcarlson** [PrismarineJS/node-minecraft-protocol#693]
If you are reporting a bug please report on these points :

The basic example of creating a client and trying to connect to a server. It is a forge server, which I understand is not a proity for this repo.

In particular it will be useful to provide these informations :

* what happens when using a node-minecraft-protocol example?
* what minecraft-protocol version? 1.11.0
* what server version? 1.15.2
* which server? (spigot, paper, vanilla, any particular plugins ?) 
* what's the output of DEBUG="minecraft-protocol" node your_script.js ?

```
  minecraft-protocol writing packet login.login_start +6ms
  minecraft-protocol { username: 'digger' } +1ms
C:\git\hivemine\node_modules\minecraft-protocol\src\transforms\framing.js:67
          } else { throw e }
                   ^

Error: Deserialization error for login.toClient : Read error for name : 27 is not in the mappings value
    at ProtoDef.readMapper (C:\git\hivemine\node_modules\protodef\src\datatypes\utils.js:30:34)
    at ProtoDef.read (C:\git\hivemine\node_modules\protodef\src\protodef.js:110:29)
    at C:\git\hivemine\node_modules\protodef\src\datatypes\structures.js:45:32
    at tryCatch (C:\git\hivemine\node_modules\protodef\src\utils.js:50:16)
    at tryDoc (C:\git\hivemine\node_modules\protodef\src\utils.js:54:10)
    at C:\git\hivemine\node_modules\protodef\src\datatypes\structures.js:44:5
    at Array.forEach (<anonymous>)
    at ProtoDef.readContainer (C:\git\hivemine\node_modules\protodef\src\datatypes\structures.js:43:12)
    at ProtoDef.read (C:\git\hivemine\node_modules\protodef\src\protodef.js:36:25)
    at ProtoDef.read (C:\git\hivemine\node_modules\protodef\src\protodef.js:110:29)
Emitted 'error' event on Client instance at:
    at FullPacketParser.<anonymous> (C:\git\hivemine\node_modules\minecraft-protocol\src\client.js:76:12)
    at FullPacketParser.emit (events.js:323:22)
    at errorOrDestroy (C:\git\hivemine\node_modules\readable-stream\lib\internal\streams\destroy.js:98:101)
    at onwriteError (C:\git\hivemine\node_modules\readable-stream\lib\_stream_writable.js:424:5)
    at onwrite (C:\git\hivemine\node_modules\readable-stream\lib\_stream_writable.js:450:11)
    at WritableState.onwrite (C:\git\hivemine\node_modules\readable-stream\lib\_stream_writable.js:160:5)
    at FullPacketParser.afterTransform (C:\git\hivemine\node_modules\readable-stream\lib\_stream_transform.js:89:3)
    at FullPacketParser._transform (C:\git\hivemine\node_modules\protodef\src\serializer.js:79:14)
    at FullPacketParser.Transform._read (C:\git\hivemine\node_modules\readable-stream\lib\_stream_transform.js:177:10)
    at FullPacketParser.Transform._write (C:\git\hivemine\node_modules\readable-stream\lib\_stream_transform.js:164:83) {
  field: 'login.toClient'
}
Thrown at:
    at readMapper (C:\git\hivemine\node_modules\protodef\src\datatypes\utils.js:30:34)
    at read (C:\git\hivemine\node_modules\protodef\src\protodef.js:110:29)
    at C:\git\hivemine\node_modules\protodef\src\datatypes\structures.js:45:32
    at tryCatch (C:\git\hivemine\node_modules\protodef\src\utils.js:50:16)
    at tryDoc (C:\git\hivemine\node_modules\protodef\src\utils.js:54:10)
    at C:\git\hivemine\node_modules\protodef\src\datatypes\structures.js:44:5
    at readContainer (C:\git\hivemine\node_modules\protodef\src\datatypes\structures.js:43:12)
    at read (C:\git\hivemine\node_modules\protodef\src\protodef.js:36:25)
    at read (C:\git\hivemine\node_modules\protodef\src\protodef.js:110:29)
    at e.message (C:\git\hivemine\node_modules\protodef\src\protodef.js:149:49)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hivemine@1.0.0 pro-server: `node  --trace-uncaught index.protocol.js mfc-mc.westus2.cloudapp.azure.com 25565`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hivemine@1.0.0 pro-server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\macarl\AppData\Roaming\npm-cache\_logs\2020-04-05T21_11_18_873Z-debug.log
```
* what's the error msg?
* what script is used (full code)?
``` js
if (process.argv.length < 4 || process.argv.length > 6) {
  console.log('Usage : node digger.js <host> <port> [<name>] [<password>]')
  process.exit(1)
}

try {
  var mc = require('minecraft-protocol');
  var client = mc.createClient({
    host: process.argv[2],
    port: parseInt(process.argv[3] || 25565),
    username: process.argv[4] ? process.argv[4] : 'digger',
    password: process.argv[5]
  });

  var forgeHandshake = require('minecraft-protocol-forge').forgeHandshake;
  var autoVersionForge = require('minecraft-protocol-forge').autoVersionForge;
  //autoVersionForge(bot._client); //, { forgeMods: [] });
  
  forgeHandshake(client, {
    forgeMods: [
      { modid: 'lucky', version: '1.15.2-1' },
      { modid: 'performant', version: '' },
      {
        modId: "lucky",
        modmarker: "1.15.2-1"
      }, {
        modId: "performant",
        modmarker: "1.7"
      }, {
        modId: "give",
        modmarker: "1.1.0"
      }, {
        modId: "nhacampfire",
        modmarker: "1.5"
      }, {
        modId: "netherpspr",
        modmarker: "2.1"
      }, {
        modId: "vilnames",
        modmarker: "2.0"
      }, {
        modId: "sulfurpotassiummod",
        modmarker: "2.3.0"
      }, {
        modId: "getinthebucketmod",
        modmarker: "2.2.0"
      }, {
        modId: "forge",
        modmarker: "ANY"
      }, {
        modId: "quark",
        modmarker: "r2.1-224"
      }, {
        modId: "healingcf",
        modmarker: "1.7"
      }, {
        modId: "autoreglib",
        modmarker: "1.5-40"
      }

    ]
  });

}
catch (e) {
  console.error(e);
}
```

**Comment by rom1504** [comment]
that's an issue for forge plugin
