### ISSUE TITLE
Cannot handle deserialization error for individual packets

### ISSUE THREAD

**Issue by Gjum** [PrismarineJS/node-minecraft-protocol#709]
Using `createClient`, when protodef fails to deserialize a packet, the whole client shuts down, and does not allow me to handle expected malformed packets.

I'm not sure if this should be fixed in protodef or nmp.

Versions: minecraft-protocol 1.11.0, protodef 1.6.10, minecraft-data 2.50.0

---

The error I'm getting in particular is this one: on 1.12.2 Bungee/Spigot with custom recipe plugin (civrealms.com)

```
Error: Deserialization error for play.toClient.declare_recipes.recipes.0.data.crafting_shapeless.result.unknown.default.nbtData.type : Read error for params.declare_recipes.recipes.0.data.crafting_shapeless.result.unknown.default.nbtData.type : 102 is not in the mappings value
    at ProtoDef.readMapper (/project/node_modules/protodef/src/datatypes/utils.js:30:34)
    at ProtoDef.read (/project/node_modules/protodef/src/protodef.js:36:25)
    at ProtoDef.read (/project/node_modules/protodef/src/protodef.js:110:29)
    at /project/node_modules/protodef/src/datatypes/structures.js:45:32
    at tryCatch (/project/node_modules/protodef/src/utils.js:50:16)
    at tryDoc (/project/node_modules/protodef/src/utils.js:54:10)
    at /project/node_modules/protodef/src/datatypes/structures.js:44:5
    at Array.forEach (<anonymous>)
    at ProtoDef.readContainer (/project/node_modules/protodef/src/datatypes/structures.js:43:12)
    at ProtoDef.read (/project/node_modules/protodef/src/protodef.js:36:25) {
  field: 'play.toClient.declare_recipes.recipes.0.data.crafting_shapeless.result.unknown.default.nbtData.type'
}
```

**Comment by rom1504** [comment]
If you listen to error event it should not crash

**Comment by Gjum** [comment]
What emitter do I need to listen on? I'm listening on `Client` and the deserializer is already listened to in `minecraft-protocol/src/client.js:66` (`setSerializer`).

<details><summary>Minimal example:</summary>

```javascript
const mcProto = require('minecraft-protocol')

const client = mcProto.createClient({
  host: process.env.MC_HOST || "localhost",
  username: process.env.MC_USERNAME || "McProto",
  password: process.env.MC_PASSWORD,
})

process.on("unhandledRejection", err => {
  console.error(`[ERROR] process.unhandledRejection error=${err}`)
  console.error(err)
})
process.on("uncaughtException", err => {
  console.error(`[ERROR] process.uncaughtException error=${err}`)
  console.error(err)
})
process.on("warning", err => {
  console.error(`[WARNING] process.warning error=${err}`)
  console.error(err)
})

client.on('error', err => {
  console.error(`[ERROR] error error=${err}`)
  console.error(err)
})
client.on('kicked', packet => {
  console.error(`[ERROR] kicked reason=${packet.reason}`)
})
client.on('end', payload => {
  console.error(`[ERROR] end reason=${payload}`)
})
client.on('disconnect', packet => {
  console.error(`[ERROR] disconnected reason=${packet.reason}`)
})
client.on('close', () => {
  console.error(`[ERROR] connection closed`)
})
client.on('timeout', () => {
  console.error(`[ERROR] connection timeout`)
})

let pos
client.on('position', packet => {
  pos = packet
  if (packet.teleportId) {
    client.write('teleport_confirm', { teleportId: packet.teleportId })
  }
})

client.once('position', () => {
  this.tickInterval = setInterval(() => {
    client.write('position_look', { onGround: true, ...pos })
  }, 50)
})
```

</details>

**Comment by sgdc3** [comment]
I got the following error trying to connect to a server using 1.14.4 as client version: https://paste.lucko.me/ROwYEVJ811
I used the example code in the README file.

**Comment by rom1504** [comment]
Can you post the server too

**Comment by sgdc3** [comment]
The server was play.tecnocraft.net

**Comment by rom1504** [comment]
`client.on('error', () => {})` works fine for me

**Comment by MartinzX24** [comment]
I'm having the same issue,`client.on('error', () => {})` doesn't stop the process from crashing
my server has fabric mods

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/client.js#L68 this should be a pb
