### ISSUE TITLE
Error when running basic program

### ISSUE THREAD

**Issue by Footsiefat** [PrismarineJS/node-minecraft-protocol#719]
```
/home/paul/Documents/minecraftprograms/node_modules/minecraft-protocol/src/transforms/framing.js:67
          } else { throw e }
                   ^

TypeError: Cannot read property 'fishing_bobber' of undefined
    at inject (/home/paul/Documents/minecraftprograms/node_modules/mineflayer/lib/plugins/inventory.js:20:38)
    at /home/paul/Documents/minecraftprograms/node_modules/mineflayer/lib/plugin_loader.js:26:7
    at Array.forEach (<anonymous>)
    at injectPlugins (/home/paul/Documents/minecraftprograms/node_modules/mineflayer/lib/plugin_loader.js:25:13)
    at Bot.onInjectAllowed (/home/paul/Documents/minecraftprograms/node_modules/mineflayer/lib/plugin_loader.js:12:5)
    at Object.onceWrapper (events.js:416:28)
    at Bot.emit (events.js:310:20)
    at Client.next (/home/paul/Documents/minecraftprograms/node_modules/mineflayer/index.js:119:12)
    at Object.onceWrapper (events.js:416:28)
    at Client.emit (events.js:322:22)
    at /home/paul/Documents/minecraftprograms/node_modules/minecraft-protocol/src/client/autoVersion.js:53:12
    at Client.<anonymous> (/home/paul/Documents/minecraftprograms/node_modules/minecraft-protocol/src/ping.js:28:7)
    at Object.onceWrapper (events.js:417:26)
    at Client.emit (events.js:310:20)
    at FullPacketParser.<anonymous> (/home/paul/Documents/minecraftprograms/node_modules/minecraft-protocol/src/client.js:87:12)
    at FullPacketParser.emit (events.js:310:20)
    at addChunk (/home/paul/Documents/minecraftprograms/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/home/paul/Documents/minecraftprograms/node_modules/readable-stream/lib/_stream_readable.js:280:11)
    at FullPacketParser.Readable.push (/home/paul/Documents/minecraftprograms/node_modules/readable-stream/lib/_stream_readable.js:241:10)
    at FullPacketParser.Transform.push (/home/paul/Documents/minecraftprograms/node_modules/readable-stream/lib/_stream_transform.js:139:32)
    at FullPacketParser._transform (/home/paul/Documents/minecraftprograms/node_modules/protodef/src/serializer.js:81:10)
    at FullPacketParser.Transform._read (/home/paul/Documents/minecraftprograms/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at FullPacketParser.Transform._write (/home/paul/Documents/minecraftprograms/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/home/paul/Documents/minecraftprograms/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/home/paul/Documents/minecraftprograms/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at FullPacketParser.Writable.write (/home/paul/Documents/minecraftprograms/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at Splitter.ondata (/home/paul/Documents/minecraftprograms/node_modules/readable-stream/lib/_stream_readable.js:681:20)
    at Splitter.emit (events.js:310:20)
    at addChunk (/home/paul/Documents/minecraftprograms/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/home/paul/Documents/minecraftprograms/node_modules/readable-stream/lib/_stream_readable.js:280:11)
    at Splitter.Readable.push (/home/paul/Documents/minecraftprograms/node_modules/readable-stream/lib/_stream_readable.js:241:10)
    at Splitter.Transform.push (/home/paul/Documents/minecraftprograms/node_modules/readable-stream/lib/_stream_transform.js:139:32)
    at Splitter._transform (/home/paul/Documents/minecraftprograms/node_modules/minecraft-protocol/src/transforms/framing.js:61:16)
    at Splitter.Transform._read (/home/paul/Documents/minecraftprograms/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at Splitter.Transform._write (/home/paul/Documents/minecraftprograms/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/home/paul/Documents/minecraftprograms/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/home/paul/Documents/minecraftprograms/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Splitter.Writable.write (/home/paul/Documents/minecraftprograms/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at Socket.ondata (_stream_readable.js:695:22)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)

```

**Comment by rom1504** [comment]
Can you please give more information ? (Follow the template)

**Comment by rom1504** [comment]
But anyway this should be open in mineflayer, not here

**Comment by Footsiefat** [comment]
`var mineflayer = require('mineflayer');
var bot = mineflayer.createBot({
  host: "localhost", // optional
  port: 25565,       // optional
  username: "email@example.com", // email and password are required only for
  password: "12345678",          // online-mode=true servers
  version: false                 // false corresponds to auto version detection (that's the default), put for example "1.8.8" if you need a specific version
});
bot.on('chat', function(username, message) {
  if (username === bot.username) return;
  bot.chat(message);
});
bot.on('error', err => console.log(err))`

there is the example code I was running which I filled into my email:password and a server(pika.host).

Im using node v12.16.3 and npm 6.14.4

**Comment by rom1504** [comment]
What minecraft version ?

**Comment by Footsiefat** [comment]
pika.host is a multi version server. but I belive its originaly 1.8 or 1.9

**Comment by Footsiefat** [comment]
Tried it with another server, thats 1.15.2. got a different error.

PartialReadError: Deserialization error for play.toClient : Read error for undefined : undefined

**Comment by Footsiefat** [comment]
@rom1504 I got it working, turns out it doesnt work on some servers :( 

But I got a new problem. I tried to use the [https://github.com/PrismarineJS/mineflayer/blob/master/examples/quitter.js](https://github.com/PrismarineJS/mineflayer/blob/master/examples/quitter.js) To get it to disconnect as soon as it connects, but it never quits the server.

**Comment by Footsiefat** [comment]
Got it working.
