### ISSUE TITLE
Ticking screen crash while connected to server.

### ISSUE THREAD

**Issue by gjz010** [PrismarineJS/node-minecraft-protocol#94]
I tried to connect to an example server(npm install node-minecraft-protocol) using Minecraft 1.7.6,but the client crashed.
```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 14-7-23 18:34
Description: Ticking screen

java.lang.NullPointerException: Ticking screen
	at com.mojang.util.UUIDTypeAdapter.fromUUID(UUIDTypeAdapter.java:22)
	at com.mojang.util.UUIDTypeAdapter.write(UUIDTypeAdapter.java:13)
	at com.mojang.util.UUIDTypeAdapter.write(UUIDTypeAdapter.java:10)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:89)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:195)
	at com.google.gson.Gson.toJson(Gson.java:593)
	at com.google.gson.Gson.toJson(Gson.java:572)
	at com.google.gson.Gson.toJson(Gson.java:527)
	at com.google.gson.Gson.toJson(Gson.java:507)
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:52)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.joinServer(YggdrasilMinecraftSessionService.java:60)
	at blj.a(SourceFile:47)
	at jt.a(SourceFile:41)
	at jt.a(SourceFile:10)
	at ej.a(SourceFile:166)
	at bcr.c(SourceFile:78)
	at ban.p(SourceFile:1342)
	at ban.ak(SourceFile:773)
	at ban.f(SourceFile:727)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.jackhuang.hellominecraftlauncher.Launcher.main(Launcher.java:175)
	at org.jackhuang.hellominecraftlauncher.Main$7.onDone(Main.java:190)
	at org.jackhuang.hellominecraftlauncher.Main$7.onDone(Main.java:187)
	at org.jackhuang.hellominecraftlauncher.GameLauncher.executeEvent(GameLauncher.java:102)
	at org.jackhuang.hellominecraftlauncher.GameLauncher.makeLaunchCommand(GameLauncher.java:260)
	at org.jackhuang.hellominecraftlauncher.Main.main(Main.java:193)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.mojang.util.UUIDTypeAdapter.fromUUID(UUIDTypeAdapter.java:22)
	at com.mojang.util.UUIDTypeAdapter.write(UUIDTypeAdapter.java:13)
	at com.mojang.util.UUIDTypeAdapter.write(UUIDTypeAdapter.java:10)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:89)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:195)
	at com.google.gson.Gson.toJson(Gson.java:593)
	at com.google.gson.Gson.toJson(Gson.java:572)
	at com.google.gson.Gson.toJson(Gson.java:527)
	at com.google.gson.Gson.toJson(Gson.java:507)
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:52)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.joinServer(YggdrasilMinecraftSessionService.java:60)
	at blj.a(SourceFile:47)
	at jt.a(SourceFile:41)
	at jt.a(SourceFile:10)
	at ej.a(SourceFile:166)
	at bcr.c(SourceFile:78)

-- Affected screen --
Details:
	Screen name: bcr
Stacktrace:
	at ban.p(SourceFile:1342)
	at ban.ak(SourceFile:773)
	at ban.f(SourceFile:727)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.jackhuang.hellominecraftlauncher.Launcher.main(Launcher.java:175)
	at org.jackhuang.hellominecraftlauncher.Main$7.onDone(Main.java:190)
	at org.jackhuang.hellominecraftlauncher.Main$7.onDone(Main.java:187)
	at org.jackhuang.hellominecraftlauncher.GameLauncher.executeEvent(GameLauncher.java:102)
	at org.jackhuang.hellominecraftlauncher.GameLauncher.makeLaunchCommand(GameLauncher.java:260)
	at org.jackhuang.hellominecraftlauncher.Main.main(Main.java:193)

-- System Details --
Details:
	Minecraft Version: 1.7.6
	Operating System: Linux (i386) version 3.13.0-32-generic
	Java Version: 1.8.0_05, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Server VM (mixed mode), Oracle Corporation
	Memory: 82815448 bytes (78 MB) / 115740672 bytes (110 MB) up to 2120679424 bytes (2022 MB)
	JVM Flags: 2 total; -Xincgc -Xmx2048m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.7.6
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 7560D GL version 4.3.12798 Compatibility Profile Context 13.35.1005, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
```
I think it may have something to do with the library as I can connect to my Bukkit server well,but I don't know how to solve this problem.Hope for your help.Sorry for bad English.

**Comment by roblabla** [comment]
This should have been fixed. Closing.
