### ISSUE TITLE
Buffer Error

### ISSUE THREAD

**Issue by justin97530** [PrismarineJS/node-minecraft-protocol#95]
Okay, so I officially need help...

I get this when I try to log in... In the scenario I use the serverhelloworld example and value and offset are 0 and 2 respectively.

```
Justins-Mac-mini:Cactus justin$ node main

buffer.js:784
    throw TypeError('value is out of bounds');
          ^
TypeError: value is out of bounds
    at TypeError (<anonymous>)
    at checkInt (buffer.js:784:11)
    at Buffer.writeInt32BE (buffer.js:924:5)
    at Array.writeLong [as 1] (/Users/justin/Desktop/MacBook/Minecraft/Servers/Cactus/node_modules/minecraft-protocol/lib/protocol.js:1049:10)
    at write (/Users/justin/Desktop/MacBook/Minecraft/Servers/Cactus/node_modules/minecraft-protocol/lib/protocol.js:1231:17)
    at /Users/justin/Desktop/MacBook/Minecraft/Servers/Cactus/node_modules/minecraft-protocol/lib/protocol.js:1281:14
    at Array.forEach (native)
    at createPacketBuffer (/Users/justin/Desktop/MacBook/Minecraft/Servers/Cactus/node_modules/minecraft-protocol/lib/protocol.js:1278:10)
    at Client.write (/Users/justin/Desktop/MacBook/Minecraft/Servers/Cactus/node_modules/minecraft-protocol/lib/client.js:154:16)
    at Server.<anonymous> (/Users/justin/Desktop/MacBook/Minecraft/Servers/Cactus/main.js:29:10)
```

**Comment by roblabla** [comment]
UUID has been fixed somewhere, this issue is no more. Closing.
